### ISSUE TITLE
BlockPos and Dimension ID per Angel?

### ISSUE THREAD

**Issue by ReallySub** [ReallySub/Weeping-Angels-Mod#10]
In show, when the Doctor is explaining the angels to Billy Shipton, he says 'Touched of an angel, same one probably since you ended up in the same year' (https://youtu.be/8LqmAQwHNA0 @ 00:19 onwards)

Which gave me the idea of assigning each angel a random block position and dimension ID that they send the entity they touch to

Basically, A random position and dimension given separately to every angel for use

Thoughts?

**Comment by 50ap5ud5** [comment]
This sounds like an interesting concept. I could see this could tie in to the hunger mechanic that the angels have in order to sustain themselves.

**Comment by ReallySub** [comment]
Decided to implement this.
