### ISSUE TITLE
i died to a weeping angel now i am a ghost please help

### ISSUE THREAD

**Issue by bradley8737** [ReallySub/Weeping-Angels-Mod#112]
so i was playing crazy craft 3 and this has happened to me twice within 3 years i stopped playing after it first happened 3 years ago as it took all of my hearts and my head keeps jerking to the left then the right really violently heres an image as you can see i have 0 hearts still alive cant access my inventory and we removed the more health mod thinking that was the issue but it caused another person to have the same problem so we put it back and i thought it might be this mod since i was killed by an angel each time we have also deleted my playerdata  and it didnt change anything infact my stuff i had on me is still there somehow
![image](https://user-images.githubusercontent.com/64857182/81090859-98189d80-8ebb-11ea-9489-989d2accdd4c.png)

**Comment by Jeryn99** [comment]
I'm really sorry to inform you, but the mod you're using isn't my one. I didn't make the original version and if I remember correctly the author for that version of the mod is no longer active. I have nothing to do with the original version and only have the model shown in the image you have provided as a tribute to them. 

I'm really sorry to hear of this problem though and that I can't do anything about it.
