### ISSUE TITLE
[1.14.4] Angels teleporting after their death.

### ISSUE THREAD

**Issue by zelotbe** [ReallySub/Weeping-Angels-Mod#113]
When a player kills a weeping angel with a pickaxe they are still able to teleport you or do other harmful effects.
Happened twice so far in the overworld :)

**Modpack:** Tardis Engineers
https://www.curseforge.com/minecraft/modpacks/tardis-engineers/files

**Comment by Jeryn99** [comment]
You mean like, once the angel is destroyed and drops stone, it can still teleport you?

**Comment by zelotbe** [comment]
Exactly 😄 , They dropped stone and I go back to what I was doing and after a few seconds the teleportation happens.

**Comment by Jeryn99** [comment]
Sorry for late reply, are you sure this is not just lag? They can only teleport you while living..

**Comment by Jeryn99** [comment]
This should be fixed, if it happens again, comment and I'll reopen
