### ISSUE TITLE
The weeping angel_3 has no texture on 1.14.4

### ISSUE THREAD

**Issue by avidbiscuit** [ReallySub/Weeping-Angels-Mod#114]
![2020-07-07_16 12 58](https://user-images.githubusercontent.com/50924190/86802305-ce65cb00-c06c-11ea-9d04-835f44f862bf.png)

**Comment by Jeryn99** [comment]
Natually spawned or with a spawn egg?

**Comment by avidbiscuit** [comment]
> Natually spawned or with a spawn egg?

Both. I spawned one and then found this one in a cave with no texture. It’s the same story with the arm in the snow but I had spawned it

**Comment by Jeryn99** [comment]
Thank you, I will address this soon

**Comment by avidbiscuit** [comment]
> Thank you, I will address this soon

Thank you. I’ll now close this as it has been addressed and you are aware of this issue

**Comment by Jeryn99** [comment]
Has now been addressed.
