### ISSUE TITLE
Crash Report 1.14.4

### ISSUE THREAD

**Issue by avidbiscuit** [ReallySub/Weeping-Angels-Mod#115]
Game keeps crashing on 1.14.4. Here is the crash log

[crash-2020-07-09_10.15.47-server.txt](https://github.com/Swirtzly/Weeping-Angels/files/4895756/crash-2020-07-09_10.15.47-server.txt)

**Comment by 50ap5ud5** [comment]
Hi, there's a new build of Weeping Angels that addresses this issue. Could you please install the latest version and test if the same issues can be reproduced?

**Comment by avidbiscuit** [comment]
> Hi, there's a new build of Weeping Angels that addresses this issue. Could you please install the latest version and test if the same issues can be reproduced?

Yes, I'll see if it can be reproduced. Thank you for letting me know

**Comment by Jeryn99** [comment]
Should be fixed by https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/2995765
Please leave a comment if the issue still persists after updating.
