### ISSUE TITLE
Crashing whenever encountering angel

### ISSUE THREAD

**Issue by whydoesthisexist69420** [ReallySub/Weeping-Angels-Mod#118]
something seems to be wrong. everytime i play it crashes. heres the report: https://drive.google.com/file/d/1uy-veXmS7bl_kVXQYqMHXpRvZGwGmGQ4/view?usp=sharing and heres what first showed up: https://drive.google.com/file/d/1iHmG1-EXa7mBzI4gOMWtiBt-B0OemVWQ/view?usp=sharing

**Comment by Jeryn99** [comment]
Thank you for creating this issue, we will attempt to fix this through this issue and upload a build here for you to test once the issue is resolved, would you be willing to test the new jar once it is created to see if your issue is resolved?

**Comment by whydoesthisexist69420** [comment]
i could try, but im not sure itll be 100% accurate. coz im pretty sure it doesnt happen all the time, but yeh, sure

**Comment by whydoesthisexist69420** [comment]
if i encounter the issue on later releases, i will let you know

**Comment by whydoesthisexist69420** [comment]
if, you know, i dont encounter it right away

**Comment by 50ap5ud5** [comment]
You are using an old build of Weepings Angels, 2.1.6. Does this issue happen consistently in the latest version (2.1.7)?

**Comment by whydoesthisexist69420** [comment]
sorry, i copy pasted from a comment from the last version. i was sure i edited it to show the crash with 2.1.7. however, i still encountered it with 2.1.7. heres the actual report: https://drive.google.com/file/d/1vOuGT5jEz0N5JmXEL5BfSukySjGG4JNj/view?usp=sharing

**Comment by 50ap5ud5** [comment]
Hi, what I meant by using 2.1.7 is actually downloading the weeping-angels-2.1.7.jar from Curseforge. You only renamed the file, that does not change the version of the mod.

**Comment by whydoesthisexist69420** [comment]
hang on, what? i did download the mod. was i supposed to delete the config file or something? i did download the jar file. is it saying that its just renamed? thats strange. i have no idea whats happening

**Comment by Jeryn99** [comment]
Ignore 50, it seems whoever did the last release did not change the version number by one 

I'll look more into this issue, there might be something up with our build.gradle or something like that

**Comment by whydoesthisexist69420** [comment]
alright

**Comment by whydoesthisexist69420** [comment]
imma just go to sleep for now

**Comment by Jeryn99** [comment]
Download Weeping Angels 2.1.8 when it releases :)
