### ISSUE TITLE
Unknown Game Crash 1.14.4

### ISSUE THREAD

**Issue by PhantomTheDev** [ReallySub/Weeping-Angels-Mod#119]
I am running the latest version at this time. This same crash has occurred numerous times. I am not sure the exact cause, as it seems random. 

Crash Report:
https://pastebin.com/zkEAJ5sF

**Comment by Jeryn99** [comment]
"Oh no, not again!" - Eighth Doctor 

I don't know what causes this error and I've been investigating it for a long time, was this on a server or on the client? 
And do you also have a latest.log and a debug.log FROM the event of the crash?

**Comment by PhantomTheDev** [comment]
This particular crash was on the client. However, it did also happen while I was hosting a LAN world. Here is a link to the debug and latest log from the crash. This is in a modpack I am making, so they are a little bloated. ----> https://drive.google.com/drive/folders/1l_rVx6lEf-tZbqfOLs5iJPqP8JWRFVln?usp=sharing

**Comment by Jeryn99** [comment]
Interesting, you've been the most helpful person when providing information for this crash

@50ap5ud5, it seems my theory solved 1/2 classes that encounter this problem, moving your looting enchantment stuff to a pre-existing class that is seen by the game seems to have done the trick. But not the same for poses, perhaps we could make them a Forge Registry instead?

This way a new class is created and would crash the game INSTANTLY if the class does not exist, meaning we can debug this easier if changing the way it works does not fix anything.

**Comment by PhantomTheDev** [comment]
I'm glad I can help! My friends and I love this mod and cant wait for it to be fully functional.

**Comment by Jeryn99** [comment]
I'm glad!

I've started rewriting a massive chunk of what makes it crash, wanted to avoid doing that for a while but it seems like I've ran from the inevitable too long 

Should be sorted for around this time tomorrow

**Comment by 50ap5ud5** [comment]
@Swirtzly That's good to hear. I think making the Poses a ForgeRegistry could help, but we'd need to test this. Maybe the users could help us with this once we release the patch. :)

**Comment by Jeryn99** [comment]
So this commit here should end this game-breaking crash, but I can't confirm it with my use alone 
https://github.com/WhoCraft/Weeping-Angels/commit/c3273b3bb9a1a614e738d37952361c815a552d39


So if I could ask you to test this release here and get back to me as soon as you can 👍  
https://github.com/WhoCraft/Weeping-Angels/releases/tag/2.1.8

**Comment by PhantomTheDev** [comment]
I will throw that in my modpack and test it out as soon as possible. I hope it works!

**Comment by Jeryn99** [comment]
Good luck!
