### ISSUE TITLE
[request] Dimension Whitelist/Blacklist

### ISSUE THREAD

**Issue by Xules01** [ReallySub/Weeping-Angels-Mod#12]
If you have time, I would like to be able to have the angels only spawn in one dimension.  For me that would be the deep dark.

**Comment by ReallySub** [comment]
I guess I'll see what I can do

**Comment by Sketaful** [comment]
Shouldn't this be possible with a spawn-mod?

**Comment by ReallySub** [comment]
Been meaning to close this, this is, indeed managable with a external mod
