### ISSUE TITLE
Angela Model has no texture when spawned in through creative menu

### ISSUE THREAD

**Issue by avidbiscuit** [ReallySub/Weeping-Angels-Mod#120]
I have spawned in the Angela Model to check out the new poses added in the newest update but it comes up purple and black.
See the image below for more details
![2020-08-17_13 25 52](https://user-images.githubusercontent.com/50924190/90396109-8e433080-e08d-11ea-8e60-70bd2f069569.png)

**Comment by Jeryn99** [comment]
Can I have a log

**Comment by avidbiscuit** [comment]
the game doesn't crash, it just doesn't load the model. How can I get you a game log?

**Comment by Jeryn99** [comment]
When it occurs, pause the game
Head over to your Minecraft installation
Go to the logs folder
Upload latest log on http://gist.github.com
Link it to me

**Comment by avidbiscuit** [comment]
I reloaded the game and the issue fixed itself. If I see it again I will reupload it

**Comment by Jeryn99** [comment]
Is this without or without optifine installed?
