### ISSUE TITLE
Keep crashing with this error log every time I leave my TARDIS

### ISSUE THREAD

**Issue by avidbiscuit** [ReallySub/Weeping-Angels-Mod#121]
[crash report.txt](https://github.com/WhoCraft/Weeping-Angels/files/5091955/crash.report.txt)

**Comment by Jeryn99** [comment]
Could you test with this jar and tell me if the issue still persists? https://github.com/WhoCraft/Weeping-Angels/releases/tag/3.0.2

**Comment by avidbiscuit** [comment]
the issue has fixed itself, thank you

**Comment by Jeryn99** [comment]
is that with the new jar?

**Comment by avidbiscuit** [comment]
yes
