### ISSUE TITLE
weeping angel texture is black and purple- latestlog included

### ISSUE THREAD

**Issue by avidbiscuit** [ReallySub/Weeping-Angels-Mod#122]
[19Aug2020 19:50:47.497] [Client thread/WARN] [net.minecraft.client.renderer.texture.TextureManager/]: Failed to load texture: weeping_angels:textures/entities/angel_2.png
java.nio.channels.ClosedChannelException: null
[latest.log](https://github.com/WhoCraft/Weeping-Angels/files/5098676/latest.log)

this line of code is close to the bottom of the latest log as I closed the game straight after
However, the issue resolves itself when you close and reload the game

**Comment by Jeryn99** [comment]
https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3037056
