### ISSUE TITLE
snow biomes lock up the game

### ISSUE THREAD

**Issue by Portal-Jumper-79** [ReallySub/Weeping-Angels-Mod#123]
any time I go near a snow biome my game locks up, I can't teleport away and chunks won't load. This also seems to crash my friends forge server (I can't confirm this as my friend is having trouble removing the mod from the server but it seems a likely candidate). Removing the weeping angels mod fixes the problems I had with my game locking up.

Mod version: 1.14.4-3.0.1
Game version: 1.14.4-forge-28.2.0
Other mods that I had in my folder: jei-1.14.4-6.0.0.29   Tardis-Mod-1.14.4-1.3.1   create-mc1.14.4_v0.2.3   Xaeros_Minimap_20.20.0_Forge_1.14.4    OptiFine_1.14.4_HD_U_F5

**Comment by Jeryn99** [comment]
Crash report?

**Comment by Portal-Jumper-79** [comment]
after talking to my friend in never really crashed, he had to close it manually, but the server would still lock up and neither of us could connect.

**Comment by Jeryn99** [comment]
In that case, I need you to go to the servers log directly after its shut down once this issue occurs and to send me latest.log and debug.log (if it exists) from the servers log folder

**Comment by Portal-Jumper-79** [comment]
my friend seems to be busy rn so I'll try and start a server myself without the mod, I did go into single player and tried creating a buffet world that was all snowy tundra and the game locked up at 0% of generation, I will send the latest.log and debug.log from that
[debug.log](https://github.com/WhoCraft/Weeping-Angels/files/5110917/debug.log)
[latest.log](https://github.com/WhoCraft/Weeping-Angels/files/5110920/latest.log)

**Comment by Jeryn99** [comment]
I'll see if I can re-write the way the arms in snow generate, the current way looks pretty scuffed

**Comment by Portal-Jumper-79** [comment]
I assumed that would have caused the problem, hopefully whatever causes this bug is fixed because I would like to use this mod when messing around with the tardis

**Comment by Jeryn99** [comment]
Does turning the arms off in the config help you at all?

**Comment by Portal-Jumper-79** [comment]
how would I do that?

**Comment by Jeryn99** [comment]
Forget that, does creating a buffet world with this version here help you this issue? 

https://github.com/WhoCraft/Weeping-Angels/releases/tag/3.0.3

**Comment by Portal-Jumper-79** [comment]
I tried creating a buffet world that was only a snow biome and the game locked up at 0%

**Comment by Jeryn99** [comment]
With the above version, I just gave you?

**Comment by Portal-Jumper-79** [comment]
oh did not see that sorry, ill test it right now

**Comment by Portal-Jumper-79** [comment]
it loads now, I'll try and get on the server with my friend later to try it there

**Comment by Portal-Jumper-79** [comment]
thanks for the help my game loads without locking up.

**Comment by Jeryn99** [comment]
Cool! I released the linked version on CurseForge!
