### ISSUE TITLE
Angels can teleport people to the nether roof.

### ISSUE THREAD

**Issue by KingDomino** [ReallySub/Weeping-Angels-Mod#124]
Just as the title says. I was teleported to the Nether Roof by an arm in the snow on Galifrey. It should be noted that I was actually teleported with my lower half in the top layer of the bedrock. I'm not a coder or anything but I recommend that  if the player is being sent to the nether then it can't be with a Y level over 120 (not sure if that's easy to do, also not trying to tell you how to do your job, just a suggestion). I'm going to go find a way to get down now, thanks for looking at this.
[latest.log](https://github.com/WhoCraft/Weeping-Angels/files/5127234/latest.log)
![Screenshot_296](https://user-images.githubusercontent.com/53811250/91248583-d1df0f80-e709-11ea-8d96-a688e96b038a.png)

**Comment by Jeryn99** [comment]
Will be fixed next update. You'll need to use creative to dig down in the mean time.

**Comment by Jeryn99** [comment]
Fixed in latest 1.16.2 and latest 1.14.4
