### ISSUE TITLE
Server crash when angels attempt to teleport

### ISSUE THREAD

**Issue by 10595870** [ReallySub/Weeping-Angels-Mod#126]
[latest.log](https://github.com/WhoCraft/Weeping-Angels/files/5194920/latest.log)
Logs attatched
Is it possible to disable angels teleporting? In the config files I could only see how to change the distance they attempted to teleport you. 

Thanks for any help - I feel like this is a very stupid question from me.

**Comment by Jeryn99** [comment]
You can disable it by changing teleport to none

Buuuut, your forge is just out of date
