### ISSUE TITLE
Crashes & odd behavior in 1.16.3 

### ISSUE THREAD

**Issue by MLMII** [ReallySub/Weeping-Angels-Mod#129]
Minecraft:  1.16.3
Forge:  34.1.14
Angels:  1.0.1

While testing the mod I made a creative world and when attempting to place down the angels the game doesn't crash, but all entities just freeze and I can break and place blocks, but nothing drops, any commands entered into the console doesn't work, and if I throw something on the ground it leaves my inventory but simply disappears.

Now, I can place down the angel arm sticking out of the snow; but when I ran into it in order to test the teleporting the game crashed with the following log.   

[crash-2020-10-08_22.55.23-server.txt](https://github.com/WhoCraft/Weeping-Angels/files/5352614/crash-2020-10-08_22.55.23-server.txt)

**Comment by Jeryn99** [comment]
I'll address the crash issue tonight, but as for the lag goes, does it still happen with "arms" disabled in the config?

**Comment by MLMII** [comment]
Yes; it also happens when I'm just flying around looking for Angels using the Timey Whimey Detector (I tried turning the exploding chickens setting off but that didn't make a difference.); although in that case its when the Detector goes into its faster clicking sound which I assume means an angel is close).

**Comment by Jeryn99** [comment]
Try with arms turned off and get back to me.

**Comment by MLMII** [comment]
Sorry for the confusion but I did and toggling the generation of the arms doesn't seem to have an effect.

**Comment by Jeryn99** [comment]
https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3075721


So this was a really dumb problem, I made a typo when retrieving the config option for Angel speed
Instead if using ``get`` I used ``hashCode`` (How I managed this, I have no idea, I was probably half asleep)
But this made the game try and make the angels way too fast, faster than the game could update, and caused this lag
