### ISSUE TITLE
Weeping Angel teleporting to bad places

### ISSUE THREAD

**Issue by Mnigos** [ReallySub/Weeping-Angels-Mod#132]
Weeping Angel can teleport u to another dimention and u can't escape from 'em cause u don't have the teleport, and he can teleport u above the bedrock in nether and to block and u die cause u bug in the block

**Comment by Jeryn99** [comment]
What minecraft version? What forge version? What mod version?

**Comment by Mnigos** [comment]
Minecraft version 1.12.2, Forge version 1.12.2-14.23.5.2838, Mod version 46.

**Comment by Jeryn99** [comment]
I don't support 1.12 versions as much anymore. Sorry.
