### ISSUE TITLE
[1.16.3-4] Kontron Ore still spawns when genOres = false

### ISSUE THREAD

**Issue by bessiq** [ReallySub/Weeping-Angels-Mod#134]
Weeping-Angels-1.16.x-1.0.4 and 1.0.5
Tested on Forge: 34.1.42 (full modpack), 35.0.15 (no other mods)

No errors or relevant info in logs.

**Comment by Jeryn99** [comment]
When you say still spawns, is this on a world you created BEFORE disabling it?

**Comment by bessiq** [comment]
Yes, brand new single player worlds.

**Comment by Jeryn99** [comment]
Ahh, I see
I'll look more into this, thank you so much for reporting
