### ISSUE TITLE
server crash 

### ISSUE THREAD

**Issue by ruurdjee** [ReallySub/Weeping-Angels-Mod#137]
if i come near a weeping angel or one tp's to me the server crashes. how can i fix this?

**Comment by Jeryn99** [comment]
By uploading the crash report so I can see what's wrong.

**Comment by ruurdjee** [comment]
how can i do that?

**Comment by ruurdjee** [comment]
Server thread/ERROR Encountered an unexpected exception
25.11 19:55:01 [Server] INFO java.lang.NoSuchMethodError: net.minecraft.block.BlockState.func_215696_m(Lnet/minecraft/world/IBlockReader;Lnet/minecraft/util/math/BlockPos;)Z
25.11 19:55:01 [Server] INFO at me.swirtzly.minecraft.angels.utils.WATeleporter.yCoordSanity(WATeleporter.java:28) ~[weeping_angels:1.0.6] {re:classloading}
25.11 19:55:01 [Server] INFO at me.swirtzly.minecraft.angels.common.entities.WeepingAngelEntity.lambda$teleportInteraction$2(WeepingAngelEntity.java:371) ~[weeping_angels:1.0.6] {re:classloading}
25.11 19:55:01 [Server] INFO at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
25.11 19:55:01 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
25.11 19:55:01 [Server] INFO at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
25.11 19:55:01 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
25.11 19:55:01 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
25.11 19:55:01 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
25.11 19:55:01 [Server] INFO at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
25.11 19:55:01 [Server] INFO at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
25.11 19:55:01 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B}
25.11 19:55:01 [Server] INFO at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:695) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
25.11 19:55:01 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
25.11 19:55:01 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
25.11 19:55:01 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211] {}
25.11 19:55:01 [Server] Server thread/FATAL [ne.mi.co.ForgeMod/]: Preparing crash report with UUID c7dd1d37-d821-4770-b6d9-5dd481f776ce
25.11 19:55:04 [Multicraft] Server shut down (running)
25.11 19:55:04 [Multicraft] Not restarting crashed server.
25.11 19:55:04 [Multicraft] Server stopped

**Comment by ruurdjee** [comment]
this is all i can find of the crash

**Comment by ruurdjee** [comment]
and the weeping angels also dont follow me when i turn around

**Comment by Jeryn99** [comment]
Update Forge to latest build.

**Comment by ruurdjee** [comment]
still have the problem

**Comment by ruurdjee** [comment]
this is what it says now
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 11/25/20 8:06 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.block.BlockState.func_215696_m(Lnet/minecraft/world/IBlockReader;Lnet/minecraft/util/math/BlockPos;)Z
	at me.swirtzly.minecraft.angels.utils.WATeleporter.yCoordSanity(WATeleporter.java:28) ~[weeping_angels:1.0.6] {re:classloading}
	at me.swirtzly.minecraft.angels.common.entities.WeepingAngelEntity.lambda$teleportInteraction$2(WeepingAngelEntity.java:371) ~[weeping_angels:1.0.6] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:695) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (amd64) version 4.18.0-20-generic
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1014117200 bytes (967 MB) / 1419247616 bytes (1353 MB) up to 2863661056 bytes (2731 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xmx3072M -Xms128M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.4.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.4.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.4.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.4.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.4.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.4
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.4-server.jar                    |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.4-universal.jar                 |Forge                         |forge                         |35.1.4              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Weeping-Angels-1.16.x-1.0.6.jar                   |Weeping Angels                |weeping_angels                |1.0.4               |DONE      |NOSIGNATURE
		Morpheus-1.16.4-4.2.68.jar                        |Morpheus                      |morpheus                      |4.2.68              |DONE      |NOSIGNATURE
	Crash Report UUID: 5f37ca13-0b58-476d-901f-fbf95886ac98
	Player Count: 1 / 24; [ServerPlayerEntity['ruurdje'/148, l='ServerLevel[world]', x=-339.93, y=80.00, z=-606.68]]
	Data Packs: vanilla, mod:forge, mod:morpheus (incompatible), mod:weeping_angels (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Jeryn99** [comment]
Will be investigated in #138
