### ISSUE TITLE
Is it possible to let us set minimumSpawn to 0?

### ISSUE THREAD

**Issue by No3371** [ReallySub/Weeping-Angels-Mod#139]
Just asking, because It seems like it will keep popping up after getting killed.

**Comment by No3371** [comment]
Or maybe something that mark a chunk that angels try not to move in would be good.

The main reason is that the ability to remove lights are interesting so I like it, but it would be a bad experience for players try hard to build a nice home, so...

**Comment by 50ap5ud5** [comment]
Have you tried adjusting the config file spawn rate settings?

**Comment by No3371** [comment]
All the spawn/biome values are set to 1.
I was testing my modpack, and saw 2 angels stands together after not a long time since login.
Killed them and moving around then meet another 1 after just a while.

**Comment by No3371** [comment]
I'm wondering what's the design purpose you decided the 1~ range for? Do you want that "there's always a angel every biome so always a angle stalking near players"?

**Comment by No3371** [comment]
My player told me that he dived under water today and found 10+ angels 👼 
So maybe it's not not just about the config values?

**Comment by No3371** [comment]
With CrashUtilities, I can see that there are 280+ angels serverwide, and this is only a 5 player servers.

**Comment by No3371** [comment]
https://forums.minecraftforge.net/topic/93746-1164-mincount-and-maxcount-seemingly-ignored-in-biome-spawns/
So it seems minSpawn/maxSpawn decide how many for each spawn op, not a uplimit of the mob?

**Comment by No3371** [comment]
As min spawn is not what I thought ("min angels per biome"), the issue is solved for me. I am using InControl to deal with the over spawning so It's not a problem for now.

I'll leave the issue to you to decide to close or not.

**Comment by Jeryn99** [comment]
Sorry for the slow reply from me to this thread, a busy day. I will need to make Spawning configurations more clear within the config, but could you let me know what Minecraft version you are referring to? I am going to close this but you can still comment

**Comment by No3371** [comment]
1.16.3 👍
