### ISSUE TITLE
Excessive angel spawning

### ISSUE THREAD

**Issue by G-Stav** [ReallySub/Weeping-Angels-Mod#140]
![2020-12-07_11 49 45](https://user-images.githubusercontent.com/18726116/101349010-e7c5aa00-388c-11eb-9908-940dd496f705.png)
For some reason angels will repeatedly spawn and wander into quarks large cave lava lakes. I saw a few on the border in spectator trying to spot why I was experiencing fps issues, and then saw what I deem an excessive amount under the lava. I tried limiting their spawns with incontrol, but after a switch to peaceful and back to normal mode, they started accumulating again.

**Comment by Jeryn99** [comment]
What minecraft version my guy?

**Comment by G-Stav** [comment]
1.16.4, forge 35.1.7, Weeping Angels 1.16.x-1.0.7

After some further experimentation, something else odd which might have something to do with it, it appears if the angels spawn below the block.
![2020-12-07_21 17 36](https://user-images.githubusercontent.com/18726116/101400674-8a078100-38d1-11eb-9f53-754ff3f17bf0.png)

**Comment by Jeryn99** [comment]
Could I have a copy of your config file?

**Comment by G-Stav** [comment]
https://pastebin.com/qs5kraXU tried with spawnWeight = 100 and = 1

**Comment by Jeryn99** [comment]
Did this excessiveness happen before or after you changed the config?

**Comment by G-Stav** [comment]
I think before, I just tried deleting the config and regenerating a fresh config, and they're not spawning -as- frequently, but they're still spawning under the blocks instead of on them.

**Comment by 50ap5ud5** [comment]
Ignore the accidental closing of the issue, I am working to address this issue but will keep this issue open for now, until it's fully resolved.

**Comment by 50ap5ud5** [comment]
Hi @G-Stav, just to clarify, is your issue report about the Weeping Angels spawning in weird locations, such as below blocks?
