### ISSUE TITLE
Invincible angels

### ISSUE THREAD

**Issue by kubistonek** [ReallySub/Weeping-Angels-Mod#149]
Seems like in worlds with updated version of this mod (from older to latest) all angels (even recently spawned) are invincible unless hit with diamond pickaxe specifically (iron doesn't work)

No idea how this would work, I tried recording it in obs but accidentally didn't focus on window, but I will re-record it later

config untouched, and it works okay in newly created worlds, so probably not config fault

+ Idk if it's on purpose but when playing with shades after hitting angel the sun/moon texture glitches untill teleported

and angels don't despawn like orther mobs

**Comment by kubistonek** [comment]
version 1.16.5, mod version: at least most recent from Feb 16, and 2 previous

**Comment by Jeryn99** [comment]
- Shaders change Minecraft Rendering a lot, this sun and moon texture glitch is not fixable by me at least
- Just fixed the despawning issue

You wouldn't happen to be playing on HARD difficulty would you?

**Comment by Jeryn99** [comment]
Try this for me please https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3205897

**Comment by kubistonek** [comment]
I ll try this asap.

And yes I'm playing on hard, never thought that you did difficulty scaling on this mob, great idea, I just didn't see anything about it and it confused me.

**Comment by Jeryn99** [comment]
Use this link instead https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3206137
