### ISSUE TITLE
Improve coffins

### ISSUE THREAD

**Issue by rafaelkai** [ReallySub/Weeping-Angels-Mod#150]
Just a suggestion, the coffin icon feels a little bit out of place and they do not have sounds when opening, thank you.

**Comment by Jeryn99** [comment]
Been thinking the same!

**Comment by Jeryn99** [comment]
https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3206137

**Comment by rafaelkai** [comment]
Isn't it the same version as before? I already have 2.0.5

**Comment by Jeryn99** [comment]
Yes, but also no
There were a few minor changes made to blockstates, if the previous link was downloaded and put on a server and then people tried to join with the new link, crashes would occur 

It also fixes structures a little bit and fixes a loot table producing far too many timey wimey detectors

Speaking of servers, I would love to be hit up with the server you guys are playing on
