### ISSUE TITLE
Angles teleporting to lava / under bedrock

### ISSUE THREAD

**Issue by kubistonek** [ReallySub/Weeping-Angels-Mod#151]
Angels can sometimes teleport you to lava / (under bedrock (not sure about this)

default config with teleport radius set to 10000 and teleport type to structure

I don't know if lava teleporting is on purpose though, but I don't like it

**Comment by Jeryn99** [comment]
This bug will be in both Fabric and Forge verisons, but can I ask which one you are using?

**Comment by kubistonek** [comment]
Forge
