### ISSUE TITLE
[BUG] and [Question]

### ISSUE THREAD

**Issue by crhis612** [ReallySub/Weeping-Angels-Mod#153]
Hello ! 
I had question regarding the way to kill the weeping angels, is there a way to make them only killable through the Chrondyne Generator ? I thought it was a good way to make them harder to kill than just building a pickaxe and hitting them (which seems to break shaders).

Also, i noticed that in the last version 1.16.x enven though the hardcore mode was activated they were still killable and didn't destroy any blocks (though this might be because of some other mods i use so i don't really know, i tried searching the configs of all mods but didn't find anything.

Sincerely
M.

**Comment by Jeryn99** [comment]
Shaders Problem: Could you upload a video here and show me that? I will see what I can do about it because I haven't personally experienced the issue 

I'm kinda done with the idea of hardcore mode, instead now I will be creating a different config type

**Comment by Jeryn99** [comment]
This will be how it works from the next update onwards, if you have any questions, please ask:

	#Allowed Values: NOTHING, ANY_PICKAXE_AND_GENERATOR_ONLY, ANY_PICKAXE_ONLY, DIAMOND_AND_ABOVE_PICKAXE_ONLY, GENERATOR_ONLY

	damageType = "ANY_PICKAXE_AND_GENERATOR_ONLY"

**Comment by Jeryn99** [comment]
https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3221683

**Comment by crhis612** [comment]
[image: image.png]
I don't have anything to record my screen, so here is a screenshot, this
happens when a crack appears on the weeping angel, each time there are more
cracks it becomes a bit worse, and it all comes back to normal after
destroying him. (i have BSL, but i do think it does bug with other shaders,
friends told me so at least) this might be due to the high number of mods i
have however i didn't try to do this with no mods so i don't know for sure.
Wow, you updated quick ! Thanks it's amazing !

M.

**Comment by Jeryn99** [comment]
There is no image attached to this

**Comment by crhis612** [comment]
https://prnt.sc/109fpas

There you go !
