### ISSUE TITLE
[BUG] Angels still killable no matter what the setting is.

### ISSUE THREAD

**Issue by Jusey1** [ReallySub/Weeping-Angels-Mod#154]
With the new update (2.0.7), a new config was added. So I regenerated my config and attempt to change it. No matter what I have it on, ALL pickaxes and generators will always be able to kill the angels. The only thing that could change is whether or not normal attacks will work on them. Forge Version is 36.0.43 when tested.

**Comment by Jeryn99** [comment]
That's strange, could you upload your config here please?

**Comment by Jusey1** [comment]
[config.zip](https://github.com/WhoCraft/Weeping-Angels/files/6058703/config.zip)

**Comment by Jeryn99** [comment]
So is your intention to make them invincible?

**Comment by Jeryn99** [comment]
I am stupid. I left my testing settings on
Download this version: https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3222604
