### ISSUE TITLE
Mixin error on Fabric 1.16.5

### ISSUE THREAD

**Issue by magistermaks** [ReallySub/Weeping-Angels-Mod#155]
The problem is caused by invalid mixin definition, the "ServerMixin" (i assume) should be server only:
```
"server": [
    "ServerMixin"
 ]
```
in _weeping_angels.mixins.json_, i can't tell by looking at that class if this is fixing the problem or only the symptoms.  

And about the missing OroConfig - the `build.gradle` looks ok, maybe check if you uploaded the right file to curseforge (the one without the -dev and -sources at the end) as that could also explain the mixin problems.

**Comment by Jeryn99** [comment]
Thanks! I'll get right onto fixing that tomorrow
Sorry that this happened

**Comment by Jeryn99** [comment]
This should have fixed it: https://www.curseforge.com/minecraft/mc-mods/the-lonely-assassins/files/3223802
