### ISSUE TITLE
Weeping Angel Spawn Issues + Catacomb Crash

### ISSUE THREAD

**Issue by JKaiya** [ReallySub/Weeping-Angels-Mod#156]
Catacombs crashes player game back to main menu on Shockbyte server when entered/touched. Additionally Weeping Angels do not seem to be spawning in all 1.165s, only tested most recent 3. Lastly 1.64 teleporting player above Nether and excessive spawning(?).

**Comment by Jeryn99** [comment]
Crash reports?

**Comment by JKaiya** [comment]
> Crash reports?

Sorry, I don't remember... We also decided to use another server instead as we've been having problems with Shockbyte. I had posted this issue once we decided to give up and revert to most recent 1.64 version of this mod. However, we discovered new bugs. This time they are spawning, however, there seems to be too much spawning. They are also falling into lava and staying there it seems. Also when it teleports you, you teleport above the nether on that version, which is okay on creative but not survival. I'm guessing this was fixed in the newer versions though.

Basically the issues we had with the 1.65 versions was that we could not find a weeping angel anywhere other than manually spawning it from the egg, and also when we entered a catacomb, close enough to touch any brick there, it crashes. The server is still up, however, any player that got crashed is not able to rejoin the game as it automatically kicks them out and had some line thing which was likely to be the crash report which I don't remember about... This was yesterday. I do want to note that the catacombs did not crash the game when played in single-player, this is why I think it has something to do with Shockbyte.

I also noticed that no angels seem to be spawning in 1.65s, I've only spent 1-2 hours searching through caves, but I have not been able to find them on both server/singleplayer. Are the spawns extremely rare in the newest versions? As I had mostly been flying through caves so they might've not had time to spawn. Lastly I wish to note that if Weeping Angels are supposed to be spawning in catacombs and cemetaries we have not found any even when camping in there for a while. If it is not rare spawns, then I feel like the spawning might be a mod conflict as we have 27 mods installed. I feel like the most likely culprits are one of these generation mods which I will put links to below as they have things related to cave generation.

https://www.curseforge.com/minecraft/mc-mods/yungs-better-caves
https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge
https://www.curseforge.com/minecraft/mc-mods/subterranean-wilderness (We deleted this and still same so likely not this)
https://www.curseforge.com/minecraft/mc-mods/quark (we had deleted this for a period of time before deciding to readd it and we still had same problem, so likely not this either)
https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures

**Comment by Jeryn99** [comment]
I have edited your title and initial message. Generally, the problem goes into the description but that's fine
The Spawns are controllable on your end, you have a config section dedicated to them, I am not very good at assigning spawns so this may be why there are too many (I think I gave them the same rate as zombies)

The 1.16.5 version of the mod is the same as the 1.16.4 version because they all run on the same jar due to how small changes between 1.16.3 and 1.16.5 were, it is strange that this affects spawning

The catacomb crash worries me as this may not have to do with ShockByte, so I would like a crash report uploaded here if it happens again, I'm sure you know where to locate them, but incase you do not you can find all crash reports from a server in a folder called "crash-reports" in the root directory of the server, I would need the one from this crash to find out what is going on so I can prevent this for other people. So please, if it happens again, upload the newest crash report immediately 

You have not left what version of the mod you are using, could you please give me the jars filename?

**Comment by JKaiya** [comment]
We used the original files of what was available on the forge website: https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod as we do not know how to configure them as we aren't able to in Minecraft mods for whatever reason unless a mod is made to config inside Minecraft.
The 1.165 versions we tried were the most recent 3 uploads (the ones where we couldn't find a weeping angel spawn and catacomb crashes player on server)
For the 1.164 version it was the most recent one of that (For the *teleporting* [not spawning] you above nether and seemingly mass spawning).

I'm not actually the owner of the server as my friend is, and he might've already refunded/shutdown that server, he also might not be willing to do this. I am really interested in this mod though so I'll ask and hopefully, he can do redownload the 1.165 version and do the crash report thing. We are one of the few who don't know about how to find the crash reports, but I'll forward what you said to him. As we are getting a new server site tomorrow, we will definitely check with the new server site, but no guarantees on the ShockByte or if he's willing to find crash report thing as not sure how complicated that is.

**Comment by Jeryn99** [comment]
The config folder is located at the root of the server directory
I'll await any more information you can give on it

**Comment by JKaiya** [comment]
[latest.log](https://github.com/WhoCraft/Weeping-Angels/files/6070881/latest.log)
Is this is? Also he just checked with our new server hosted at BiSect hosting and it still crashes when we touch/enter a catacomb.
The Minecraft message we get when the player is crashed out to main menu is "connection lost [next line] internal server error [next line] back to server list"

**Comment by Jeryn99** [comment]
I found the problem, it will be fixed within the next few minutes and then I will link you the download

**Comment by Jeryn99** [comment]
https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3224247

**Comment by JKaiya** [comment]
Thanks, it works now. Weeping Angels also spawn now in case that was glitched too
