### ISSUE TITLE
Angels face only one direction

### ISSUE THREAD

**Issue by Casterborous** [ReallySub/Weeping-Angels-Mod#157]
While using the mod in a server, the angels will only face north

**Comment by Jeryn99** [comment]
Interesting!
Thank you for reporting, I will be sure to look into it

Could you please leave your Mod Version + Minecraft Version and a screenshot?
Does this affect all models or just one?

**Comment by Jeryn99** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Investigate why Weeping Angels sometimes only face one direction](https://trello.com/c/K1rWMxtQ/33-investigate-why-weeping-angels-sometimes-only-face-one-direction)

**Comment by Casterborous** [comment]
Hi there, terribly sorry about the very late reply.

The issue was sorted with a new mod version.

But I would like to know how to reduce the spawn frequency, as the config
file seems to do nothing.

**Comment by Jeryn99** [comment]
I'm going to close this as the facing issue is fixed, but the spawning issue is a separate issue
#140 is where you would want to go and voice your issues with it
