### ISSUE TITLE
Kontron Ore Config

### ISSUE THREAD

**Issue by ghost** [ReallySub/Weeping-Angels-Mod#158]
Add configurable variables to Kontron ore generation allowing users to change:
- The chance Kontron ore veins spawn
- The size of each Kontron ore vein

This would give the mod greater compatibility with other ore generation mods

**Comment by 50ap5ud5** [comment]
Hi, did you know in the 1.16 versions of this mod you can use Minecraft Datapacks to adjust them yourself without needing the mod author to add configurable options for you?

All you have to do is make a Configured Feature json in your datapack. This Configured Feature will be able to replace the instance originally in the mod and you can configure the ore vein size etc. all within the json.

For more information visit the Minecraft Wiki: https://minecraft.gamepedia.com/Custom_world_generation

**Comment by ghost** [comment]
> Hi, did you know in the 1.16 versions of this mod you can use Minecraft Datapacks to adjust them yourself without needing the mod author to add configurable options for you?
> 
> All you have to do is make a Configured Feature json in your datapack. This Configured Feature will be able to replace the instance originally in the mod and you can configure the ore vein size etc. all within the json.
> 
> For more information visit the Minecraft Wiki: https://minecraft.gamepedia.com/Custom_world_generation

I didn't realize datapacks would work with forge mods! Thank you for the heads up, I'll use this method for now.

**Comment by Jeryn99** [comment]
I am not sure I can make this configurable in code, as @50ap5ud5 said, a datapack is the best way :)
