### ISSUE TITLE
Crash on Fabric 1.16.5

### ISSUE THREAD

**Issue by itsNordLord** [ReallySub/Weeping-Angels-Mod#159]
Crashlog: https://paste.gg/p/anonymous/15ff6650f6b7492da2a8caee290e073f
Loaded mods (if there are any incompatibilities I wasn't aware of): https://paste.gg/p/anonymous/34bdef6b286644289e908575bf3679f5
Mod version 1.0.2

**ISSUE**:
Game crashes when traveling
Catacombs (and probably graveyards) do not obey config option and still generate even when disabled
Weeping Angels function fine without crashing when spawned in a static environment

Also the Timey Wimey detector seems to play its audio after unequipping the item for a few seconds

EDIT: Seems like a worldgen bug, game will hang when generating a singleplayer world occasionally, issue goes away with mod removed.

**Comment by Jeryn99** [comment]
Hey there
I support the Forge version primarily, so it may be up to a few days before I address this issue, as for your other issue #160 
I will fix this first, release, and then consider config options for it

**Comment by Jeryn99** [comment]
Hi, what Fabric loader version are you using?

**Comment by itsNordLord** [comment]
> 
> 
> Hi, what Fabric loader version are you using?

Most recent - 0.11.3 on 1.16.5, and my FabricAPI version is 0.32.5.

**Comment by Jeryn99** [comment]
This has been fixed now
It will be released within the next build of weeping angels, I will add a link here when that is released
I have a few other things to address with the Fabric version first

**Comment by Jeryn99** [comment]
https://www.curseforge.com/minecraft/mc-mods/the-lonely-assassins/files/3272251
