### ISSUE TITLE
Crashed client when on server

### ISSUE THREAD

**Issue by Sketaful** [ReallySub/Weeping-Angels-Mod#16]
Updated to he latest version and after a while on my server I run on another machine I got a client crash. Now I can't login without getting the same crash. Something about "vehicle"? 

https://paste.dimdev.org/amiqipizex.txt

**Comment by ReallySub** [comment]
All players: 1 total; [EntityPlayerSP['sketaful'/9704, l='MpServer', x=-500.47, y=78.00, z=-493.88]]

Looks like I forgot a !world.isRemote check, so some server code probably leaked onto the client
Does the server itself crash or just the client?

**Comment by Sketaful** [comment]
Only the client.

**Comment by ReallySub** [comment]
Does this happen to all users or just yourself?

**Comment by Sketaful** [comment]
That's a trick question since I am the only player on the server. :P

I'm messing around with my own custom pack and some friends will join in when I stabilized it some, but atm it's only me. :)

**Comment by ReallySub** [comment]
Drat haha, got any steps to re-produce this error? Essentially just logging in right?

**Comment by Sketaful** [comment]
I logged in and messed around with CustomNPC for a while which basically means I stood still. I would belive a Weeping Angel just spawned during this time and that's what crashed it.

No idea what else would have done this but I'll go through my logs as well. The version before this one worked without any problems so something must have changed.

**Comment by Sketaful** [comment]
Hmmm... I am curious about the line in the crashlog:
"Entity's Vehicle: ~~ERROR~~ NullPointerException: null"

In my debug-log I got:
"[main/WARN] [net.minecraft.client.network.NetHandlerPlayClient]: Received passengers for unknown entity"

**Comment by ReallySub** [comment]
That's a normal MC thing, it's just saying `Hey, I don't have anything riding me`
I fixed your issue though, just compiling it for you to test

**Comment by ReallySub** [comment]
Try this out for me: https://github.com/ReallySub/Weeping-Angels-Mod/releases/tag/12.5

**Comment by Sketaful** [comment]
Oh. What was it? :D

**Comment by ReallySub** [comment]
As I thought, I used server code on the client by mistake ;-;

**Comment by Sketaful** [comment]
You are a god! :D 
Tried spawning a Weeping Angel and it broke, updated with the update you posted and everything worked perfectly.

Also let the Wa attack me (had set it on 100% tp) and it teleported me at once. I ended up 3 blocks under ground suffocating, but that it avtually a nice extra danger ;D

**Comment by ReallySub** [comment]
I should really write better teleporting code...another time maybe hahaha
Glad your issue is sorted!
