### ISSUE TITLE
[REQUEST] Additional config options for Fabric

### ISSUE THREAD

**Issue by itsNordLord** [ReallySub/Weeping-Angels-Mod#160]
I know Forge is the main platform for this mod, but there are a few options that could make Weeping Angels more flexible for modpack authors:

- Whitelist for dimension ID's that Angels can warp to
- Warp range or warp coordinates or warp to spawn (always warp within ~25 blocks would keep the player within Stalk Range, always warp to 0 ~ 0 could be useful for adventure maps)
- Disable Angel warp entirely
- Disable Angel immunity to traditional weapons
- Allow Timey Wimey detector to work without being held or give us other options for detection 
- Config descriptions (what does `chickenBoom` do? what does `breakBlocks` do specifically?)
- Angel health (diamond pickaxe does 1/10th of an Angel's health)

Default options sound like they would make larger modpacks hard to play because the Angel's are very presence-dominating. If we could adjust them into the role of a powerful and rare mob they would fit right into place.

**Questions**:
- Do config options `movementSpeed` & `spawnWeight` accept decimals? Modmenu does not allow decimal input
- How and where do Angels spawn? Like traditional mobs or always a chance to spawn around the world?

**Comment by Jeryn99** [comment]
Hey there, going forward to Fabric 1.17, there will be a lot more configuration options
