### ISSUE TITLE
Weeping Angels just delete themselves when activated - Fabric

### ISSUE THREAD

**Issue by xandercreates** [ReallySub/Weeping-Angels-Mod#161]
Upon activating a Plinth or a Statue block with redstone the angels just despawn instantly,
Here is a video to show this.

https://user-images.githubusercontent.com/69139978/114206063-f26e7980-9928-11eb-9ba3-d1124ec0daa7.mp4

**Comment by Jeryn99** [comment]
~Are you playing on Peaceful?~

**Comment by 50ap5ud5** [comment]
Does this occur if Weeping Angels is the only mod that is installed?

**Comment by Jeryn99** [comment]
https://www.curseforge.com/minecraft/mc-mods/the-lonely-assassins/files/3272251

**Comment by xandercreates** [comment]
I was not on peaceful

**Comment by Jeryn99** [comment]
Irs fixed regardless
