### ISSUE TITLE
crash detector to angel

### ISSUE THREAD

**Issue by satt105** [ReallySub/Weeping-Angels-Mod#163]
Good morning,
I have a bug with the weeping angel.
the angel detector systematically stops the game
I put you the crash log
[crash-2021-04-28_16.02.40-client.txt](https://github.com/WhoCraft/Weeping-Angels/files/6392444/crash-2021-04-28_16.02.40-client.txt)
Do you need the server logs?
I wish you a good day

**Comment by Jeryn99** [comment]
1.14.4 correct?

**Comment by satt105** [comment]
Yes

**Comment by Jeryn99** [comment]
Not to do with the Detector but instead to do with how the Timey Wimey Detector interfaces with Tardis Mod 
I will sort it soon

**Comment by satt105** [comment]
thank you very much

**Comment by Jeryn99** [comment]
Fixed, will be uploaded when I release 1.16s new version
