### ISSUE TITLE
Weeping angels cause blocks to go transparent with shaders on

### ISSUE THREAD

**Issue by ItsMeVexas** [ReallySub/Weeping-Angels-Mod#166]
Anytime an angel takes damage and i have shaders on all stone and wood disappears, not sure why this is the case but a pretty weird bug nonetheless

**Comment by Jeryn99** [comment]
Screenshots.....?

**Comment by ItsMeVexas** [comment]
![2021-06-29_11 39 07](https://user-images.githubusercontent.com/86536535/123716433-a9e2ae80-d8ce-11eb-83a2-9780366b6251.png)
![2021-06-29_11 38 48](https://user-images.githubusercontent.com/86536535/123716439-ac450880-d8ce-11eb-8920-65a4b9c4ebc3.png)
before and after

**Comment by Jeryn99** [comment]
What shaders are you using here so I can re-produce?

**Comment by Novalkyrja** [comment]
Has been happening on a server I'm managing as well, those affected are using  optifine g7 (1.16.5), SEUS shader pack. Confirming that it does not appear to affect clients without optifine installed or optifine shader packs. Default config!

Is there anything I could do, upload and/or screenshot to help diagnose?

**Comment by Jeryn99** [comment]
I have the information I need as you just provided an excellent telling of it 

I think I know what the issue is but it means I need to change how to do the cracking effect on the angels to specifically make it work for Optifine, meaning they are going to look different when I fix it 

Annoying, but it is what it is, I will have it fixed sometime this week

**Comment by Jeryn99** [comment]
Oh damn, I said a week, and now it's 23 days later
I've fixed this issue now by changing how cracks are rendered and a texture change;
I will try to remember to link the fixed version here when it is released 

![2021-07-22_19 13 47](https://user-images.githubusercontent.com/36424503/126688620-b58a645c-4c7b-461b-9b20-5b8c1c347099.png)

**Comment by Jeryn99** [comment]
https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3397421

**Comment by Novalkyrja** [comment]
> Oh damn, I said a week, and now it's 23 days later
> I've fixed this issue now by changing how cracks are rendered and a texture change;
> I will try to remember to link the fixed version here when it is released

5 days short of a horror movie, of all things
thanks for the update!
