### ISSUE TITLE
Weeping angels teleport does not check for valid locations

### ISSUE THREAD

**Issue by wilyank** [ReallySub/Weeping-Angels-Mod#169]
In our server, players have repeatedly been teleported in the air over large lava lakes, inside blocks and such.

We are playing in version 2.0.8

**Comment by Jeryn99** [comment]
What MC version? 1.16.5?

**Comment by wilyank** [comment]
Yes, version Weeping-Angels-1.16.x-2.0.8.jar on forge 36.1.4

**Comment by Jeryn99** [comment]
Thank you, I will look into this soon
Sorry that I did not see this issue before releasing a new version of the mod

**Comment by Jeryn99** [comment]
Hi there, when you say in blocks, do you mean in the nether?

**Comment by wilyank** [comment]
Indeed, that was in the nether

**Comment by Jeryn99** [comment]
Trying to patch out teleporting above lava lakes is a difficult task and somewhat takes away from the risk of being teleported, but for teleporting inside a block, I will try and fix that

**Comment by Jeryn99** [comment]
https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3397421
