### ISSUE TITLE
We keep getting disconnected from our server at random points

### ISSUE THREAD

**Issue by BLUEChester** [ReallySub/Weeping-Angels-Mod#170]
Every now and then we are randomly kicked from the server, and upon rejoining sometimes it will insta-kick us as we join, and sometimes it lets us back in. Very random

Crash report:
https://paste.gemwire.uk/view/3f6e0012

debug.log:
https://paste.gemwire.uk/view/7b0184bd

**Comment by Jeryn99** [comment]
Hi, I remember this from the Forge Discord
It seems that version of the mod had issues when compiling
I have tried to fix that at the download link below, please let me know if the issue persists, if so, I will re-open this

https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3391053
