### ISSUE TITLE
Angel Plinth doesn't remove the original fake angel after spawning the entity

### ISSUE THREAD

**Issue by SpencerMeow** [ReallySub/Weeping-Angels-Mod#171]
I noticed the "angel statue" removes the fake angel when it spawns the real one which works really perfectly but the plinth does not so it makes it look like there's 2 in the exact same place. I'm on Forge 1.16.5 (latest version)

**Comment by Jeryn99** [comment]
https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3397421
