### ISSUE TITLE
Tool Suggestion

### ISSUE THREAD

**Issue by SmartBear02** [ReallySub/Weeping-Angels-Mod#173]
It would a good idea to create a config to add  some specific tools people want to use to kill angels without reciving damage like the tinker's tools

**Comment by Jeryn99** [comment]
Hey there,
Would you prefer a tag for adding items so that this can be a data pack instead?

**Comment by SmartBear02** [comment]
soryy for the delay in my answer ive been busy. I dont know too much about modding so my idea was that the user in some way can add specific tools from other mods to fight the angels so anyway to do it is ok. Thanks for giving you some time to read it. Greetings.

**Comment by Jeryn99** [comment]
Going to close this, I will come back to this issue when I have implemented this idea
