### ISSUE TITLE
Kontron ore unable to be mined (1.17)

### ISSUE THREAD

**Issue by DestructivForce** [ReallySub/Weeping-Angels-Mod#174]
Game version: 1.17.1
Mod Version: 1.0.0
Kontron ore can't be properly be mined by any pickaxe, and there is not an assigned tool to break the block. Tested with no other mods, and with the one probe to determine assigned tool (or lack of one)

**Comment by Jeryn99** [comment]
Modrinth: https://modrinth.com/mod/weeping-angels/version/6wvQFR39
CurseForge: https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3418975
