### ISSUE TITLE
Kontron Ore duplicates the ore block with fortune (1.16)

### ISSUE THREAD

**Issue by DestructivForce** [ReallySub/Weeping-Angels-Mod#175]
Minecraft Version: 1.16.5
Mod version: 2.1.4
Instead of dropping multiple kontron crystals, or one of itself, kontron ore drops multiple of itself when broken with a fortune pickaxe. This leads to an infinite loop of free kontron ore.

**Comment by Jeryn99** [comment]
Modrinth: https://modrinth.com/mod/weeping-angels/version/6wvQFR39
CurseForge: https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3418975
