### ISSUE TITLE
[1.17.1] Default spawn rate in snow biomes is WAY over the top.

### ISSUE THREAD

**Issue by ProsperCraft** [ReallySub/Weeping-Angels-Mod#176]
weeping_angels-1.0.1

![image](https://user-images.githubusercontent.com/4427684/131576804-53db9b9b-fa5a-48b3-8898-f2257e097c0b.png)

**Comment by Jeryn99** [comment]
Hey there, 
Interesting, I'm still getting used to writing solid world-gen code for this kinda thing, I will investigate this
What is your experience with this generation in previous versions of the mod? If any 
Thank you!

**Comment by Jeryn99** [comment]
Think I have fixed this for 1.17 & 1.16 now, hit up this issue if the issue persists. New release will drop soonish
