### ISSUE TITLE
game crashes when i start new world or try to join one i have already

### ISSUE THREAD

**Issue by Thedarkladdy** [ReallySub/Weeping-Angels-Mod#177]
**Mod Version**
You can copy the name of the Jar file.
Example: Tardis-Mod-1.14.4-1.4.1 and Weeping-Angels-3.0.5

**Describe the bug**
everytime i started minecraft it crashed while loading sating there was a problem with ticking the artron collector

**To Reproduce**
1. start the game
2: try to start a world
3:should give the error messase: ![image_2021-09-06_141805](/uploads/3cbc2280b680a9af7f45471f9e6026a7/image_2021-09-06_141805.png)

**Expected behavior**
the game to load normally and let me play the game
**Screenshots and Crash reports**
You must also either attach your latest.log or the crash report related to the problem. 
[crash-2021-09-06_13.17.31-server.txt](/uploads/7793aedf68b5d0db0c8bb0ffd217c361/crash-2021-09-06_13.17.31-server.txt)
**Additional context**
i will say i have these mods and datapacks installed but this never happened any other time ive used them![image_2021-09-06_133031](/uploads/3f07b013ab2246e0b93b1e406a34d2fa/image_2021-09-06_133031.png)![image_2021-09-06_134916](/uploads/9740db9a024e81b2f72869ffbe0fbdd6/image_2021-09-06_134916.png)

P.S.: yes i know that its compatiblity related but how do i fix it

**Comment by Jeryn99** [comment]
Hi there,
You can fix this on your own by disabling Tardis Mod integration in the Weeping Angels config, I will release a fix for this some point this week
Thanks

**Comment by Jeryn99** [comment]
Closed in https://github.com/WhoCraft/Weeping-Angels/commit/592cdb118f619a84807afcc2bce7988f89973015

Download from https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3472353
