### ISSUE TITLE
Angels Not Spawning Naturally in 1.17.1

### ISSUE THREAD

**Issue by ChrisLTheNerd** [ReallySub/Weeping-Angels-Mod#179]
I'm working on a showcase for this mod but I haven't seen any weeping angels while flying across my world, even with theses configs spawnWeight = 75, maximumSpawn = 75, and minimumSpawn = 25. I'm using version "[1.17.X] Weeping Angels - 1.0.2" for 1.17.1 with forge version "37.0.67." Also I have an unrelated question, is it intended for the weeping angels to move away from the player sometimes? Sometimes I look away and they move further away from me, they only move towards me about 25-50% of the time.

**Edit: Weeping angel spawning is working in version "[1.16.X] Weeping Angels - 2.1.4" on 1.16.5 with forge version "36.2.4." They also don't have tracking issues in 1.16.5. They don't go in random directions and go straight towards me 100% of the time when looking away.**

**Comment by Jeryn99** [comment]
Hey!
This is a strange one...
For your showcase, I would use 1.16.5 until I sort this out, might be an oversight of mine between porting up to 1.17

Do link me your showcase when you're done aswell!

**Comment by ChrisLTheNerd** [comment]
I'm defiantly using the 1.16.5 version for my showcase. Also sure, I'll remember to link you to my showcase when I'm done :)
