### ISSUE TITLE
Weeping Angels Mod 1.1.6.5 crashing when player encounters new structure

### ISSUE THREAD

**Issue by avidbiscuit** [ReallySub/Weeping-Angels-Mod#182]
Mod Version
**Weeping-Angels-1.16.x-2.1.4**
**Crash Description:**
Using the TARDIS I used the structure locator upgrade to travel to a regeneration hut however when I left the TARDIS the game immediately crashed. I didn't see any weeping Angels however it seems to be an issue with the varients? I have provided both the latest.log and the crash report I hope this provides more details to help solve the issue, if you would like me to remove the mods and test the mod independently please let me know!

The Weeping Angels mod was downloaded from here:
https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod
**Crash log + latest.log:**
[crash-2021-10-06_16.38.48-server.txt](https://github.com/Suff99/Weeping-Angels/files/7295422/crash-2021-10-06_16.38.48-server.txt)
[latest.log](https://github.com/Suff99/Weeping-Angels/files/7295432/latest.log)

**Other Mods:**
![mod_list_06_10_2021](https://user-images.githubusercontent.com/50924190/136238411-2222b973-9482-4436-b5b2-b8b14c1ec633.PNG)

**Comment by Jeryn99** [comment]
There are two versions of Weeping Angels with the version number 2.1.4 due to an oversight when publishing 1.16.5;
Could you please tell me when you downloaded this version? As yesterday a new version with the version number 2.1.4 was released and I need to know if you downloaded the new version or the ancient one

**Comment by avidbiscuit** [comment]
i downloaded that version about a week ago, i will redownload it from the website and let you know if the issue persists

**Comment by avidbiscuit** [comment]
the issue has stopped, if it happens again I will reopen another issue report!
