### ISSUE TITLE
World Crash Due to Angel

### ISSUE THREAD

**Issue by oliverhunt19** [ReallySub/Weeping-Angels-Mod#185]
[crash-2021-10-07_16.36.51-server.txt](https://github.com/Suff99/Weeping-Angels/files/7305154/crash-2021-10-07_16.36.51-server.txt)
[crash-2021-10-07_16.30.15-server.txt](https://github.com/Suff99/Weeping-Angels/files/7305155/crash-2021-10-07_16.30.15-server.txt)

**Comment by Jeryn99** [comment]
Being investigated in #184 
Please keep an eye on that issue
