### ISSUE TITLE
Bug or config issue 

### ISSUE THREAD

**Issue by Flamabletheone** [ReallySub/Weeping-Angels-Mod#187]
Hi, Im having an issue with configing the angels on patch 2.1.4. To be more specific the damage dealt by the angel and the movement speed of the angel. I have had the ability to make them faster in version 12.0.7b (The only other version i could find that had reference to similar problems and the fix.) but no ability to edit damage values. I have also found that the angels seem to randomly have this issue where they cannot harm you and just teleport the player, this I have found can be solved by turning teleport type to "DONT".  My end goal with the angel config is to make them invincible and hit you extreamly hard plus teleporting you, all while being almost inescapable. Sorry if this is just me being unable to config properly, your help would be greatly appreciated.

Thanks
[weeping_angels-common.txt](https://github.com/Suff99/Weeping-Angels/files/7317664/weeping_angels-common.txt)

**Comment by Jeryn99** [comment]
Made them damage you when they teleport you now, now they will always hurt you
There is the ability to edit damage values properly going forward with 2.1.5
