### ISSUE TITLE
game crashes whenever ore mod is installed

### ISSUE THREAD

**Issue by EnderTrekkie** [ReallySub/Weeping-Angels-Mod#194]
I installed Weeping Angels, New Tardis Mod, Regen mod, and JEI, and it works fine. However, when I install a mod that adds new ores or stones, the game crashes whenever the player looks away from an angel with the missing texture pattern (magenta/black tiles).

mod version: 2.1.6
game version: 1.16.5
all other mods are up to date as of this post (23/10/21)

**Comment by Jeryn99** [comment]
Crash report please

**Comment by EnderTrekkie** [comment]
[crash-2021-10-17_18.17.50-server.txt](https://github.com/Suff99/Weeping-Angels/files/7500829/crash-2021-10-17_18.17.50-server.txt)

**Comment by EnderTrekkie** [comment]
sorry for the delay, my life got busy

**Comment by Jeryn99** [comment]
Should be fixed next version
