### ISSUE TITLE
Statues turning into incorrect angels (1.16.5)

### ISSUE THREAD

**Issue by MCraftBoatBloke** [ReallySub/Weeping-Angels-Mod#196]
When in the newest version 1.16.5, the angel statues will turn into a seemingly random angel when activated. Eg. A Villager Statue is powered and will become an Angela Angel, of any type. This happens on a server or singleplayer, creative, survival, etc. They also flinch quite a bit but I'm not sure if that is a bug meant to be removed.

**Comment by Jeryn99** [comment]
Fixed
