### ISSUE TITLE
Angel cannot jump up snowy blocks (1.16.5)

### ISSUE THREAD

**Issue by MCraftBoatBloke** [ReallySub/Weeping-Angels-Mod#199]
Angels cannot jump from one block with their feet in a layer of snow to another block with a layer of snow on top. This means they cannot really attack you well in a snowy location as you could just go a block above them that's covered in snow and they could never reach you. They can jump up the block if either the bottom or top layer of snow does not exist but in the normal snowy environment they cannot climb it.
![image](https://user-images.githubusercontent.com/95372978/144902750-d9a45210-c2a2-4515-8292-3a10979037f0.png)
They can't jump up this

**Comment by VovelPunch** [comment]
so true

**Comment by Jeryn99** [comment]
I forgot to acknowledge this on here, but I don't understand what would cause something like this? As Vanilla pathing is used

**Comment by Jeryn99** [comment]
@MCraftBoatBloke Is this still a issue?

**Comment by Jeryn99** [comment]
Lol, this was caused by such a dumb thing, fixed!
