### ISSUE TITLE
Can't disable ore generation

### ISSUE THREAD

**Issue by Xaidee** [ReallySub/Weeping-Angels-Mod#205]
When using the config file disabling ore gen doesn't actually disable ore generation, I can confirm the rest of the config file works so it seems to be ore generation specifically that is the problem.
I'm developing a modpack and ive changed some recipes and stuff and I want to remove kontron from world generation as it no longer has a use with my recipe modifications.
Really appreciate this amazing mod, thanks for your help!

	#Configure whether the mods ores spawn. This MAY require a restart when changed.
	genOres = false

And yes I've restarted the game and created new worlds multiple times with the same results.

**Comment by Jeryn99** [comment]
What Minecraft and Mod version? Ores have been re-wrote constantly

**Comment by Xaidee** [comment]
1.18 (1.0.1)

**Comment by Jeryn99** [comment]
Fixed, keep a eye out for next version

**Comment by Xaidee** [comment]
Awesome! really appreciate your work ^-^
