### ISSUE TITLE
Sometimes it is crash when I look at angels

### ISSUE THREAD

**Issue by DrSigma4164** [ReallySub/Weeping-Angels-Mod#206]
Sometimes it is beautiful when I look at angels. I found out when I removed the mod, and I stopped crashing minecraft. Before that, I had it periodically painted, now it doesn't seem to be painted, but check it out.
[crash-2022-01-19_19.27.08-client.txt](https://github.com/Suff99/Weeping-Angels/files/7899404/crash-2022-01-19_19.27.08-client.txt)

**Comment by Jeryn99** [comment]
A few users have told me that sometimes this occurs when twilightforest is installed, I need to look into it more, thanks for reporting

**Comment by Jeryn99** [comment]
Closing. Please track #212 to find out progress and ongoing solutions
