### ISSUE TITLE
Using Floral Fertilizer (Botania) then Viewing Inventory GUI (Survival) causes Forge Crash

### ISSUE THREAD

**Issue by Danekjovax** [ReallySub/Weeping-Angels-Mod#209]
Greetings,

I'm not sure where the root cause truly lies with the bug I discovered, so I am posting it with all the Githubs that are involved.  Please forgive me if I am missing something here.

Java: 1.8.0_311.b11
Modpack: Astral Engineering 1.4.2. by Elfinlocks (https://www.curseforge.com/minecraft/modpacks/astral-engineering)
Forge: 36.2.22
Minecraft 1.16.5
Mods Involved: Botania 420.1, Weeping Angels 2.1.7

![image](https://user-images.githubusercontent.com/10191173/152463052-5259e152-ea19-40ee-8ae8-26cf4ed1a393.png)

Issue: After using some Floral Fertilizer (Botania) on grass, viewing your inventory GUI will immediately produce a Forge crash (see attached 1), and then when given the option to return to the Main Menu and then clicked, sometimes results in another Forge crash (see attached 2).  Returning into the game directly from the Main Menu at this point only results in immediate crash (see crash 1), and most likely repeats crash 2.  The only way to clear this crash loop is to quit the client completely and restart the Forge client.

How to Reproduce: While in the game (using above modpack, or possibly any modpack including the two above mods), use floral fertilizer several times in an area next to you, then open your inventory GUI.  Forge should crash at this action.

Current Workaround(s): Disabling the Weeping Angels mod removed this crash event when the same actions were performed.

Thank you for your time.   Great mods!  Keep up the great work, and let's get to the bottom of these pesky bugs!

--- DanekJovax ;2
Crash Log 1
[crash-2022-02-03_17.31.04-client.txt](https://github.com/Suff99/Weeping-Angels/files/7999614/crash-2022-02-03_17.31.04-client.txt)
)

Crash Log 2
[crash-2022-02-03_17.36.06-client.txt](https://github.com/Suff99/Weeping-Angels/files/7999616/crash-2022-02-03_17.36.06-client.txt)

**Comment by Jeryn99** [comment]
#207 dupe :)
