### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by VovelPunch** [ReallySub/Weeping-Angels-Mod#211]
**Log:** [latest.log](https://github.com/Suff99/Weeping-Angels/files/8044438/latest.log)
**Debug:** [debug.log](https://github.com/Suff99/Weeping-Angels/files/8044442/debug.log)

**Comment by Jeryn99** [comment]
There is a lot to digest in this log, for example Mohist spamming the log with a Discord URL and a IP address with a port
I cannot see anything to do with Angels causing the crash here, the game seems to be crashing when trying to render a material of sorts 
If I had to guess, it may be ProtocolLib causing this
