### ISSUE TITLE
1.16.5 Render Crash

### ISSUE THREAD

**Issue by Ibirtem** [ReallySub/Weeping-Angels-Mod#212]
So, idk how this happened. All seems was fine, but in one random moment me and my friend started getting crashes. Server working fine, it's only render problem. 
1.16.5 
Forge from 22 to 28 have this issue.
https://gist.github.com/Ibirtem/0ed578b3a8abdc802a6e940939629f72

**Comment by Jeryn99** [comment]
Thanks for reporting, it will be looked into

**Comment by Jeryn99** [comment]
@Ibirtem Does this happen when you look at an angel? Needing more information about this issue to find out where in my shed loads of rendering code this occurs

**Comment by Jeryn99** [comment]
Fixed: https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3675688
