### ISSUE TITLE
Weeping Angels | 1.16.5 - 36.2.29 - 2.1.8 |

### ISSUE THREAD

**Issue by Nexusatko-zz** [ReallySub/Weeping-Angels-Mod#214]
Hello,
this update is crashing my server on start. 
Previous version 2.1.7 has no problems. 

I'm attaching the crash report below. 
[crash-2022-03-03_01.01.49-fml.txt](https://github.com/Suff99/Weeping-Angels/files/8173734/crash-2022-03-03_01.01.49-fml.txt)

**Comment by Elfinlocks** [comment]
Can concur with this - here's a snip of my server console
![image](https://user-images.githubusercontent.com/43624750/156470884-8c348615-4304-4a3f-a73e-b69fefb1b671.png)

**Comment by 50ap5ud5** [comment]
Fixed for the next version.
