### ISSUE TITLE
Server freeze for 5 minutes | Weeping Angels Entity |

### ISSUE THREAD

**Issue by Nexusatko-zz** [ReallySub/Weeping-Angels-Mod#215]
Hello,
The server froze for 5 minutes ( it kicked players, but they were still in the online players' list, etc ) and unfreeze and normally continued then. 
[crash-2022-03-05_12.12.56-server.txt](https://github.com/Suff99/Weeping-Angels/files/8191533/crash-2022-03-05_12.12.56-server.txt)
[2022-03-05-2.log](https://github.com/Suff99/Weeping-Angels/files/8191535/2022-03-05-2.log)

**Comment by Jeryn99** [comment]
Latest is 3.0.0, please try latest before reporting
