### ISSUE TITLE
failed to load correctly

### ISSUE THREAD

**Issue by PhoenixIsme** [ReallySub/Weeping-Angels-Mod#217]
[crash-2022-04-04_00.25.48-fml.txt](https://github.com/Suff99/Weeping-Angels/files/8406718/crash-2022-04-04_00.25.48-fml.txt)

dunno whats wrong or if it was my fault

**Comment by Jeryn99** [comment]
Weeping Angels is not yet ported to 1.18.2, this will come soon.
