### ISSUE TITLE
[1.16.5] angel_proof and several other block/item tags do not work

### ISSUE THREAD

**Issue by KihakuGato** [ReallySub/Weeping-Angels-Mod#218]
First thought it was just me improperly using datapacks to add angel_proof tagging (though I still wont' entirely rule that out), but it would appear weeping angels can also destroy blocks which should already be unbreakable in the default settings of angel_proof tags (ex- magma block, glowstone, sea lantern, fire,).

When inspecting the blocks with F3 it shows that the blocks are not tagged as #angel_proof. Similarly related the only time they won't break light blocks (regardless of whether they are angel_proof or not) is if they are one block away from the top of the weeping angel's head.

Upon further examination, #translucent_blocks tagged blocks also appear to have their respective tag missing.

Not sure if the same can be said for #held_light_item, or #angel_theft as I was not sure where/how to test item tags in case they also have issues.

#grave_plants tag does appear to work and those blocks have that tag intact.

**Comment by Jeryn99** [comment]
I'm gonna assume this is 1.16?

**Comment by Jeryn99** [comment]
This is now fixed
