### ISSUE TITLE
1.16.5 - Constant Log Spam - "Connection issue when retrieving Donators!" or "at me.suff.mc.angels.utils.PlayerUtil.getResponse(PlayerUtil.java:93)"

### ISSUE THREAD

**Issue by PhweeDev** [ReallySub/Weeping-Angels-Mod#219]
I am playing a normal modded survival world. but with Weeping Angels. I keep getting log spammed with stuff like this:

https://paste.gg/p/anonymous/106ee4732eee44ab8d68e6181a442827

**Comment by Jeryn99** [comment]
I’m working on it :)

**Comment by Jeryn99** [comment]
For the meantime, seems to be fixed. 
Please leave a comment if this reoccurs
