### ISSUE TITLE
How do I disable teleportation?

### ISSUE THREAD

**Issue by remixcat123** [ReallySub/Weeping-Angels-Mod#220]
I am preparing a series and I would like the angels to attack the players but not teleport them to other places.
I found in the path: Weeping-Angels/src/main/java/me/suff/mc/angels/config/WAConfig.java

> builder.push("teleport");
>         teleportType = builder.translation("config.weeping_angels.teleport_enabled").comment("Teleport Type - STRUCTURES: Teleports you to Structures Only - DONT: No Teleporting, only damage - RANDOM: Anywhere").defineEnum("teleportType", AngelUtil.EnumTeleportType.RANDOM_PLACE);
>         notAllowedDimensions = builder.translation("config.weeping_angels.disallowed_dimensions").comment("Note: This a list of dimensions that angels should NOT teleport you to.").defineList("notAllowedDimensions", Lists.newArrayList(Level.END.location().toString()), String.class::isInstance);
>         justTeleport = builder.translation("config.weeping_angels.teleport_instant").comment("just teleport. no damage.").define("justTeleport", false);
>         teleportRange = builder.translation("config.weeping_angels.teleportRange").comment("The maximum range a user can be teleported by the Angels").defineInRange("teleportRange", 450, 1, Integer.MAX_VALUE);
>         angelDimTeleport = builder.translation("config.weeping_angels.angeldimteleport").comment("If this is enabled, angel teleporting can also tp the player to other dimensions").define("angelDimTeleport", true);
>         aggroCreative = builder.translation("config.weeping_angels.aggroCreative").comment("Should Angels target creative players?").define("aggroCreative", true);
>         builder.pop();

disabling it (config.weeping_angels.teleport_disable) Or is there another way?
psdta:I am not the owner of the project, that's why I consult it, to be able to do it, thanks!

**Comment by Jeryn99** [comment]
teleportType to DONT
