### ISSUE TITLE
[1.18.2] Server hang on startup

### ISSUE THREAD

**Issue by waddon1** [ReallySub/Weeping-Angels-Mod#221]
Just added this mod to my server and it is hanging on startup it's not crashing, so I have no crash report, but I attached the server logs insted.
[latest.log](https://github.com/Suff99/Weeping-Angels/files/8717933/latest.log)
[debug.log](https://github.com/Suff99/Weeping-Angels/files/8717934/debug.log)

**Comment by Treehock** [comment]
Same with me

**Comment by Jeryn99** [comment]
Ah boy, I will get on that as soon as I can
I will post the link to the fixed download here when it is resolved 

Hopefully by tomorrow it should be sorted

**Comment by Jeryn99** [comment]
Began a fix: https://github.com/Suff99/Weeping-Angels/commit/4139d38152dfefaacfed9445547a8d6f00228f7b

Please try this file: https://data.who-craft.com/temp/weeping_angels-1.0.0.jar

Report your findings after so I can see if this is fixed and so I can release it to the public

**Comment by waddon1** [comment]
Testing now.

**Comment by waddon1** [comment]
Appears to work now

**Comment by Jeryn99** [comment]
Awesome, will have on curseforge as soon as I can

**Comment by Jeryn99** [comment]
https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3796732
