### ISSUE TITLE
Config doesn't work

### ISSUE THREAD

**Issue by masonclomid** [ReallySub/Weeping-Angels-Mod#224]
Config "pickaxes and generators only" doesn't work, the angels will take damage from any source even if it's set to true.
Uesing version 3.0.1 in 1.16.5，forge36.2.20

**Comment by Jeryn99** [comment]
Duplicate of https://github.com/Suff99/Weeping-Angels/issues/222
Please track that issue for updates

**Comment by Jeryn99** [comment]
Nevermind, it seems that the duplicate issue is for 1.12 which is no longer supported

**Comment by Jeryn99** [comment]
Hello, I'm going to need you config file, as I do not know what you mean by "set to true'

**Comment by masonclomid** [comment]
Hello. With this configuration, the angels will still take damage from other than pickaxe and generator.
![234537113](https://user-images.githubusercontent.com/101992860/174302504-39389b84-2f4b-4e39-8449-9b4c8630c8dd.png)
![984314653](https://user-images.githubusercontent.com/101992860/174302542-ecf84b12-e8ee-4c24-81ea-10ef01894afd.png)

**Comment by Jeryn99** [comment]
``pickaxeOnly`` is a legacy option, it seems I did not clean up unused config values; Sorry for that.
I have since worked on the issue you have shown and it seems it was just an oversight at the time

I have fixed this for 1.19, fixes for 1.18 and 1.16 will be coming soon

**Comment by masonclomid** [comment]
Thanks for your work

**Comment by Jeryn99** [comment]
Patched for 1.16 and 1.19
