### ISSUE TITLE
dynamic FOV ?

### ISSUE THREAD

**Issue by Adarcer** [ReallySub/Weeping-Angels-Mod#23]
https://paste.dimdev.org/wuyefexabe.mccrash

Weeping Angels 15, my FoV is not default that may helped with error.

**Comment by ReallySub** [comment]
There's a config option for this, just disable it until I look into this

Thank you

**Comment by Adarcer** [comment]
is this it cause looks disabled 
 # Camera FOV update when mouse over a angel
        B:cameraUpdate=false

**Comment by ReallySub** [comment]
That's quite odd.... You can safely go back to 14.5 on the mean time, because all thats new in 15 is a crash to do with placing paintings. I'll get a fix out this evening gmt, sorry

**Comment by ReallySub** [comment]
Fixed.
