### ISSUE TITLE
Weeping angels not spawning naturaly

### ISSUE THREAD

**Issue by rermler** [ReallySub/Weeping-Angels-Mod#230]
Hello, i have an issue with the weeping angels mod i added in the modpack of my forge (40.1.0) server in 1.18.2 . They aren't spawning naturaly even if i configured their spawn_weight at 1000 (it was originaly at 25) .
The mods i use in this server are:
-Additional Additions 4.0.0
-Alex's Mobs 1.17.5
-Architectury 4.4.65
-Backpacked 2.1.6
-Bag Of Holding 3.1.0
-Balm 3.0.3+0
-betterfpsdist mod 1.18.2-1.5
-brutalbosses mod 1.18.2-4.9
-Chunk loaders 1.1.11
-Citadel 1.11.3
-Cloth Config v4 API 6.2.62
-Collective 4.25
-Corpse 1.18.2-1.0.0
-Creeper Overhaul 1.3.0
-Dynamic Lights 1.18.6
-Easy Magic 3.3.0
-Enhanced Celestials 2.0.7
-Exotic Birds 1.4.0
-Forgiving Void 6.0.1
-Friends&Foes 1.4.0
-Geckolib 3.0.18
-Gem Crab 1.0.0
-Herobrine Awakens 1.1.1
-Incendium 0.0NONE
-Infernal Mobs 1.18.5
-InvMove 0.7.0
-Journeymap 5.8.4
-Just  Enough Items 9.7.0.195
-Layers 1.1.5
-Neat 1.8-30
-Piglin Expansion 1.1.0
-Plus The End 1.0.0
-Puzzles Lib 3.3.5
-Rare Ice 0.0NONE
-Replacing Crops 2.6
-Revamped Phantoms 0.2.3
-Shrines 1.18.2-4.0.0-beta1
-SuperMartijn642's Config Lib 1.0.9
-SuperMartijn642's Core Lib 1.0.18
-Untamed Wilds 2.1.3
-Unusual Drill Mod 2.0
-Waystones 10.0.0
-Weeping Angels 1.0.0
-Wisperwoods 1.18.2-2.1.0
-WorldEdit 7.2.10+1742f98
The list above is what i see when i open minecraft and go to mods.

**Comment by Jeryn99** [comment]
Issue has been located, will keep you updated

**Comment by Jeryn99** [comment]
Fixed in: https://github.com/Suff99/Weeping-Angels/commit/170012c4c0e8aab24edafa59194ab857c264c4ca

Please keep a eye out for the next update

**Comment by rermler** [comment]
ah thanks, so this mean i have to download the last version of the mod from curseforge?
