### ISSUE TITLE
[Feature Request] Ore Configuration 

### ISSUE THREAD

**Issue by DragonAstemirN** [ReallySub/Weeping-Angels-Mod#231]
Hello greetings.
I would like there to be a configuration for the generation of the ore, since it is generated a lot in my opinion and it is also quite abundant for crafting
![2022-05-29_16 58 17](https://user-images.githubusercontent.com/94336869/170896868-36b413d1-cc3e-4a56-8a17-9d54e0a79b0a.png)

I make the request also because in 1.12.2 this option was available if I'm not mistaken

**Comment by Jeryn99** [comment]
I mean I can do this, but I’m sure you can override it with a data pack? 

@50ap5ud5 can you confirm?

**Comment by DragonAstemirN** [comment]
Currently it is only allowed in the 1.16.5 configuration. Disable ore generation completely.
But I think it is not so good because it is part of the mod and I would like to keep it only by reducing its generation

**Comment by 50ap5ud5** [comment]
> I mean I can do this, but I’m sure you can override it with a data pack?
> 
> @50ap5ud5 can you confirm?

Unfortunately no, at least in Forge 1.16.5. The BiomeLoadingEvent fires during datapack serialisation, so any user made datapacks won't actually override the OreFeature which we define in code. In 1.18.2+ using datapacks to configure world gen is achievable with the use of Forge's BiomeModifier datapack format.
