### ISSUE TITLE
duplicate of #138 

### ISSUE THREAD

**Issue by rebarakuk** [ReallySub/Weeping-Angels-Mod#232]
version - 1.12.2
weeping angels version - 46

I didn't add twilight forest to where angels should spawn.
but the angel followed me and maybe entered to twilight forest, #138 happened.

**Comment by avidbiscuit** [comment]
Hi, please see the last comment in #138:
 
The build with the server crash fix and config fixes is now available at: https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3128433

I will close this issue now.

This issue has been closed and dealt with. The 1.12.2 version of Weeping Angels is depreciated meaning it will no longer be receiving updates or bug fixes. In the future please provide a crash log and recent.log and please do not create git issues for old versions of the mod especially if they have already been sorted and closed.
