### ISSUE TITLE
jei kontron crystal spectrometer recipe for new tardis mod 1.16.5 causing crash

### ISSUE THREAD

**Issue by TylorBane** [ReallySub/Weeping-Angels-Mod#233]
so i added a few mods to a modpack called "valhelsia 3" this one, new tardis mod, and a few others, and viewing specifically the kontron crystal spectrometer recipe through jei causes this crash https://gnomebot.dev/paste/981742260217593946 (apologies for the spooky looking link it was generated by a bot on the "modded minecraft" discord server) i also have a simular issue posted on the new tardis mod's github as well [here](https://github.com/Spectre0987/TardisMod/issues/345)

**Comment by Jeryn99** [comment]
I will look into it

**Comment by TylorBane** [comment]
is there anything you need from me?

**Comment by 50ap5ud5** [comment]
Does this issue still occur if only the New Tardis Mod and Weeping Angels Mod is installed? Perhaps one or more of the other mods in your modpack may be causing a conflict.

**Comment by TylorBane** [comment]
> Does this issue still occur if only the New Tardis Mod and Weeping Angels Mod is installed? Perhaps one or more of the other mods in your modpack may be causing a conflict.

I made a small test pack with literally only "JEI" (required to get the crash in the first place), New Tardis Mod, and Weeping Angels, total mod count 3, error still happens and viewing the "kontron crystal" recipe from Weeping Angels in the spectrometer from New Tardis causes the crash [Proof Here](https://gnomebot.dev/paste/983159532928761856)

**Comment by Jeryn99** [comment]
Fixed, please await next version
