### ISSUE TITLE
1.16 Config Issue

### ISSUE THREAD

**Issue by Arriochh** [ReallySub/Weeping-Angels-Mod#238]
pickaxeOnly = false

#Allowed Values: NOTHING, ANY_PICKAXE_AND_GENERATOR_ONLY, ANY_PICKAXE_ONLY, DIAMOND_AND_ABOVE_PICKAXE_ONLY, GENERATOR_ONLY
	damageType = "ANY_PICKAXE_AND_GENERATOR_ONLY"
	

Im still taking damage whenever I hit an angel with anything but a pickaxe. Is this supposed to be a thing regardless of this setting or what..?? Because there isn't an option for damageType = "EVERYTHING". Unless im mistaken and it isn't displayed in the config file.

**Comment by MCraftBoatBloke** [comment]
I was under the impression that this config changed what damaged the angel, not you if you were mining it.

**Comment by Jeryn99** [comment]
Config is indeed working correctly, there is no EVERYTHING option as it would make the mod too easy 

You are also punching stone, which hurts, so it hurts you
