### ISSUE TITLE
[Asset Review] 1.19+

### ISSUE THREAD

**Issue by Jeryn99** [ReallySub/Weeping-Angels-Mod#239]
Due to the mods existence since 2018, a lot of assets have joined and left. This issue is to highlight these assets and remove left over remnants of textures and sounds that are no longer used.

It should also highlight any issues with existing models in the mod such as broken animations, mistextured areas of models and visual issues

If you find any, please leave them in the comments of this issue

**Comment by avidbiscuit** [comment]
https://user-images.githubusercontent.com/50924190/173365845-a53bf31e-2ec8-49bd-ac4a-fd6214d68285.mp4

Mod name: weeping_angels-3.0.1
Game Version: 1.16.5

Issue: Broken Animation

If you require a longer video or more samples of this animation just let me know
