### ISSUE TITLE
[Request] Angel Spawn Amount & Catacomb / Graveyard Spawn

### ISSUE THREAD

**Issue by JKaiya** [ReallySub/Weeping-Angels-Mod#242]
Is it possible to lessen the angel spawn amount by a bit or add an option in the config to do so? I find that when angels spawn, they seem to all spawn in the same area, causing 10-20 angels go to me at once within a few minutes. Although I always loved the concept of weeping angels and wanted to play the mod a year to two ago (couldn't due to amount of bugs), it is a bit annoying to deal with that amount of angels. I think it should be lessened or have a option in the config to change (if there already is I'm blind).

Additionally, is there a way to find grave yards and catacombs without using the locate command? As I find these are extremely rare if not impossible to find in a natural survival playthough. Especially the catacombs as they seem to spawn around 40k-50k distance away from spawn point and at least 100k distance between 2 catacombs. These were found by the locate command when I was going around the map and testing all the mods for bugs and to see which to keep as too many is not runnable. If there isn't a way to find them, can these be increased a bit, espeically the catacombs? However, I think it'd be cooler if you add a way to find the catacombs from the graveyards, and put something special in the catacombs instead. I haven't actually played a survival game playthrough yet so not sure how these two places work other than they are unique structures you can find, with some bonus loot.

**Comment by Jeryn99** [comment]
Hi! What Minecraft version and mod version?

As every release has a configuration option for spawns, all of which can be found in the configuration file; with the exception of 1.19 as that is done through forge biome modifiers which can be changed via Data-packs


The spawn rate does need playing with, it's hard to get right to make them rare but I am working on it 

As for the far apart structures, this does need a bit of change aswell, Minecraft's ever changing worldgen makes this hard to get right

**Comment by JKaiya** [comment]
> Hi! What Minecraft version and mod version?
> 
> As every release has a configuration option for spawns, all of which can be found in the configuration file; with the exception of 1.19 as that is done through forge biome modifiers which can be changed via Data-packs
> 
> The spawn rate does need playing with, it's hard to get right to make them rare but I am working on it
> 
> As for the far apart structures, this does need a bit of change aswell, Minecraft's ever changing worldgen makes this hard to get right

I am using the newest 1.19 version. I noticed that when using the mod it seems to be the most common enemy mob that spawns. This is also likely due to them being able to spawn in the light unlike most other enemy mobs. I've done a short survival playthrough and this is a bit unplayable for me as I'll get tpd every couple minutes and eventually die. For now I'm going to try to lessen the stalk range target 25 (Edit: changed to 30 due to the rarity of attacks/stalks this caused,) in the config as I saw that was an option yesterday, to see if it'll be playable in survival with those settings.

I think another possible thing you can add, is for the angels to only target the players once it visually sees the target during a frame, from hence will target the player as long as it is within their range. This is due to angels, no matter where they spawn, are charging towards the player as long as they are within a distance range, which also might be the reason why the angels always cluster rather than a spawn issue.

**Comment by Jeryn99** [comment]
Since you have made this issue, 1.19 has received some new configurations:

- You can now change the teleport chance
- You can make anything hurt the angels
- Default spawn rate has been significantly lowered 

And these bugs have been fixed:
- Graveyards spawning at y 90 all the time 
- Spacing is being worked on

I hope these config values address your concerns, as a note, the stalk range is not exactly how you picture it. It's how many blocks around the angel it should look for players 

I did a brief playtest yesterday and I have to say I wasn't happy with how many issues cropped up, so I am working to resolve them and check on older versions to see if these same issues are present

**Comment by Jeryn99** [comment]
Patched for 1.19 and 1.16
