### ISSUE TITLE
Structures spawn in other dimensions

### ISSUE THREAD

**Issue by Answordy** [ReallySub/Weeping-Angels-Mod#245]
1.18.2
Weeping angels 1.0.1
I'm using a modpack, so it might be another mod causing it, but I can't think of any that would do such a thing.

![2022-06-18_16 12 11](https://user-images.githubusercontent.com/82783515/174448113-2da81790-3e0c-44cf-95b1-ee7893ce0e87.jpg)

**Comment by Jeryn99** [comment]
Ahh, yes this appears to be on me, I will fix this as soon as I can
