### ISSUE TITLE
[Issue / Request] Stolen Pickaxes Disappeared on Kill

### ISSUE THREAD

**Issue by JKaiya** [ReallySub/Weeping-Angels-Mod#246]
My diamond pickaxe got stolen, and although we managed to kill the angel that stole mine, I noticed that although it seemed to drop the ground, my pickaxe disappeared.  My friend was the one that killed it, and I thought I saw it go to him, however he said he didn't have it. We looked around and it seemed to disappear. 

I haven't checked the config in this version, but if there isn't, can you add a config option for them not to steal, as my friend's and I's biggest worry about the mod is them stealing for example a max enchanted netherite pickaxe, as that'll be pretty annoying as theres a possibility of not getting it back.

Used newest weeping angel mod and forge.

**Comment by Jeryn99** [comment]
I noticed this just yesterday when a friend told me about it. I'm working on it to try and find the cause of the issue.
If you do wish to disable stealing or configure it, you can download the data pack template from here: https://github.com/Suff99/Weeping-Angels/blob/1.19/Pack-Template.zip?raw=true

You will then want to find the ``angel_theft.json`` file in ``resources/data/weeping_angels/tags/items/angel_theft.json``
From there, you can configure the items it can steal or just make it black like below, which will disable the feature entirely
You then put the edited data pack into your worlds data pack folder 

```JSON
{
 "replace" : true
  "values": [

  ]
}
```

But rest assured I am working to try and find the cause as to why they are not dropping them
