### ISSUE TITLE
weeping_angels failed to load correctly

### ISSUE THREAD

**Issue by Dovahkiinthe3rd** [ReallySub/Weeping-Angels-Mod#248]
i'm new to modding Minecraft and all that so i'd like to know what i did wrong because none of the other mods failed to start like this here's the crash log

[crash-2022-08-03_15.08.39-fml.txt](https://github.com/Suff99/Weeping-Angels/files/9254468/crash-2022-08-03_15.08.39-fml.txt)

**Comment by Jeryn99** [comment]
Forge updated, I have not sorted this yet
