### ISSUE TITLE
1.19 Crash upon start-up

### ISSUE THREAD

**Issue by Godz13** [ReallySub/Weeping-Angels-Mod#249]
Hi, as said above, my game crashes for some reason whenever i use the 1.19 version of this mod, it'd say that it hasn't loaded correctly and show java.lang.reflect.InvocationTargetException: null

What can i do about it?
and here's the crash report:
[crash-2022-08-04_17.11.44-fml.txt](https://github.com/Suff99/Weeping-Angels/files/9257513/crash-2022-08-04_17.11.44-fml.txt)

Thanks,

**Comment by Jeryn99** [comment]
Fixed, it is due to Forge releasing breaking changes
