### ISSUE TITLE
Failed to load?

### ISSUE THREAD

**Issue by firestorm2039** [ReallySub/Weeping-Angels-Mod#254]
just launched game and got a message saying it failed to load
![Untitled](https://user-images.githubusercontent.com/75093996/189168968-2d311b94-09ef-47bd-81b6-2ea7a48ee1c4.jpg)

**Comment by Jeryn99** [comment]
Please give the following details:
- Forge Version 
- Minecraft Version 
- Mod version 

And your latest.log file from the logs folder

**Comment by firestorm2039** [comment]
> Please give the following details:
> 
> * Forge Version
> * Minecraft Version
> * Mod version
> 
> And your latest.log file from the logs folder

i believe
forge version is 36.1.32
minecraft version 1.18.1??? (no idea sorry)
mod version 1.0.1

as many of the mods i use are only upto 1.18.1 i cant go higher without loose most of the mods

**Comment by Jeryn99** [comment]
Some Minecraft mods work on both 1.18.1 and 1.18.2 - you should try that and see if it fixes your issue. Angels is built for 1.18.2 so doing this step is mandatory. You also did not submit that crash report that the button indicates, I will need that for more information

**Comment by Jeryn99** [comment]
Have you validated this?

**Comment by firestorm2039** [comment]
> Some Minecraft mods work on both 1.18.1 and 1.18.2 - you should try that and see if it fixes your issue. Angels is built for 1.18.2 so doing this step is mandatory. You also did not submit that crash report that the button indicates, I will need that for more information

i have removed the mod now and updated all my mods to 1.18.2, i havent tried doing the latest version of 1.18.2 of this mod yet.

sorry about not supplying a crash report, i forgot you asked you that.
