### ISSUE TITLE
1.18.2 Angels wont spawn [1.18.X] Weeping Angels - 1.0.1

### ISSUE THREAD

**Issue by Skillghost28** [ReallySub/Weeping-Angels-Mod#255]
I've created a world and then added the [[1.18.X] Weeping Angels - 1.0.1] Mod, do i need to create a new world for the angels to spawn? also the world have the ores from the mod when generating chunks.
Also turned the spawn_weight to 1000.

**Comment by Jeryn99** [comment]
I will be back porting the entire mod from 1.19.2 back to 1.18.2 for Fabric support - this will likely be sorted during that transition
