### ISSUE TITLE
Broken loot tables?

### ISSUE THREAD

**Issue by Defetyre** [ReallySub/Weeping-Angels-Mod#256]
Chests are excessively filled with items from your mod, and some of them are no longer needed after you have at least 1 of them (like radar thingy). This may cause console errors like Tried to over-fill a container.
Also why would you make a separate ore for just one item?

**Comment by Jeryn99** [comment]
https://github.com/Suff99/Weeping-Angels/issues/253

**Comment by Jeryn99** [comment]
Apologies - after re-reading I've noticed you mention something about the same item? Two ores exist for one item much like vanilla, deepslate and the original ore

The chest issue is being addressed - it was never meant to be so frequent and is now being limited to just the one loot table (Catacombs)

I appreciate you bringing your concerns to my attention - a release is due this week for angels

**Comment by Defetyre** [comment]
Sorry, i should have worded my last sentence differently. the problem i found with the ore was that it's only purpose is to craft one consumable. I suppose making a new decorative (or even functional) block for this ore could make it significantly more modpack friendly, because otherwise people can get upset at the fact that this peculiar looking block is practically pointless to mine. But this is kinda insignificant, hence why i just pointed at it in the same unrelated issue. Thank you for your efforts!

**Comment by Jeryn99** [comment]
The Timey Wimey Detector item will soon be damageable, I am still figuring out this feature - so users will have to re-craft one whenever they break and the Generator item needs to be re-crafted after use regardless. If you have any suggestions for new items or blocks for the mod I will be happy to take them
