### ISSUE TITLE
Crashing on Minecraft Startup

### ISSUE THREAD

**Issue by kayshoe** [ReallySub/Weeping-Angels-Mod#258]
Crashing on Minecraft start up. Removed the mod and it worked fine. Not really sure what this crash is but here is the debug report & crash report.

[debug (4).log](https://github.com/Suff99/Weeping-Angels/files/9595643/debug.4.log)
[crash-2022-09-18_17.43.46-client (2).txt](https://github.com/Suff99/Weeping-Angels/files/9595644/crash-2022-09-18_17.43.46-client.2.txt)

**Comment by Jeryn99** [comment]
Thanks, I will get right on this
