### ISSUE TITLE
Tinkers tools dont work as pickaxes 1.18.2

### ISSUE THREAD

**Issue by SmartBear02** [ReallySub/Weeping-Angels-Mod#259]
It would be great if there was a way to add tools that can work as pickaxes to not recive damage when hit the angels. In this case i cant use tinkers picakxes or any paxel tools form other mods. So it would be great if there was a whitelist for tools that can hurt angels. Thanks in advance :D

**Comment by Jeryn99** [comment]
Which mod version and Minecraft Version are you using here?

**Comment by SmartBear02** [comment]
Im playing on 1.18.2

**Comment by Jeryn99** [comment]
Thank you, and mod version?

**Comment by SmartBear02** [comment]
It's 1.18.x 1.0.1 release date may 19 2022
