### ISSUE TITLE
are they supposed to spawn this much?

### ISSUE THREAD

**Issue by Trinsdar** [ReallySub/Weeping-Angels-Mod#26]
![2018-07-12_23 26 50](https://user-images.githubusercontent.com/30245301/42670947-b395e6c0-862b-11e8-9350-a4a44fb9120c.png)
this is in the dim doors dungeons dimension.

**Comment by Trinsdar** [comment]
and they just keep spawning

**Comment by ReallySub** [comment]
Uhm, did you look at the config before reporting? There's options to control which biomes they don't spawn in and the rate...

**Comment by Trinsdar** [comment]
I realized after it was because no other hostile mobs spawn in those dimensions so they spawned alot.

**Comment by Trinsdar** [comment]
adding the biomes stopped them from spawing.

**Comment by ReallySub** [comment]
That's the point, there is also a config option that controls their spawn rate etc

**Comment by Trinsdar** [comment]
what about adding a dimension whitelist to the config? the only mob control mod out for 1.12 is in control and it has nothing for a dim whitelist, only a blacklist. plus it harder to understand and some people might just not understand it at all.

**Comment by nictogen** [comment]
I'm bored, I can do that

**Comment by ReallySub** [comment]
I guess I'll leave it to drake lmao, have fun @nictogen
