### ISSUE TITLE
WAMusic not being initialized

### ISSUE THREAD

**Issue by papillo12** [ReallySub/Weeping-Angels-Mod#260]
I made a modpack, I tested it and it was playable, when I shared it to some players if it let them start the game but not others, I had to ask one of those who could not enter to give me access to their pc to see what was causing it, since the crash report said that it was a bug with sound or music, then I had to discard mods from the pc of who was failing until I gave that it was the mod weeping angels, I do not know if it is an incompatibility with amd graphics as I with my nvidia graphics if I could, or if it is something sound drivers.
[crash-2022-09-17_19.23.17-client.txt](https://github.com/Suff99/Weeping-Angels/files/9620787/crash-2022-09-17_19.23.17-client.txt)
[crash-2022-09-17_18.57.40-client.txt](htt
[latest (11).log](https://github.com/Suff99/Weeping-Angels/files/9620795/latest.11.log)

[latest (7).log](https://github.com/Suff99/Weeping-Angels/files/9620789/latest.7.log)
ps://github.com/Suff99/Weeping-Angels/files/9620788/cra
[latest (8).log](https://github.com/Suff99/Weeping-Angels/files/9620790/latest.8.log)
sh-2022-09-17_18.57.40-client.txt)

**Comment by papillo12** [comment]
[crash-2022-09-17_18.57.40-client.txt](https://github.com/Suff99/Weeping-Angels/files/9620797/crash-2022-09-17_18.57.40-client.txt)
[crash-2022-09-17_18.42.30-client.txt](https://github.com/Suff99/Weeping-Angels/files/9620798/crash-2022-09-17_18.42.30-client.txt)

**Comment by Jeryn99** [comment]
I think I fixed this, just not released yet - I will send you a file to test and have you let me know if it is resolved for you

Try this: https://mc.craig.software/Weeping-Angels-43.0.7-forge.jar - just replace your current file with this one

**Comment by Jeryn99** [comment]
Did that fix it?

**Comment by papillo12** [comment]
hello, I think if the bug that made the game crash at startup was fixed, but there is another bug, the angels took away the swords to some and could no longer recover and for some reason they killed the angels and returned a pickaxe instead of a sword

**Comment by Jeryn99** [comment]
Please create a separate issue report for this

> hello, I think if the bug that made the game crash at startup was fixed, but there is another bug, the angels took away the swords to some and could no longer recover and for some reason they killed the angels and returned a pickaxe instead of a sword
