### ISSUE TITLE
Weeping Angel and TARDIS Mod Crash (1.16.5)

### ISSUE THREAD

**Issue by MianReplicate** [ReallySub/Weeping-Angels-Mod#262]
Game Version: 1.16.5
ModLoader: Forge
Forge Version: 36.2.39
Weeping Angel Mod Version: 36.0.1
Tardis Mod Mod Version: 1.5.4

- What Happens?
I was just testing this mod's compatibility with NTM and I noticed that the Weeping Angels make the TARDIS take off when they are in it. I was experimenting with this a bit and I wanted to see if they'd take off even when I was outside the TARDIS since I was inside the TARDIS when they tried taking off. I went out, used "/tardis setup" on my TARDIS so the components would automatically set themselves up without me going inside and well the game crashed! Not sure why but it did.

- How to Reproduce
1. Get Weeping Angels in the TARDIS
2. Turn off components or let them turn the components off so you can exit without them already taking off
3. Use "/tardis setup" on the TARDIS
4. Game crashed, woolah!

- Crash Log
https://mclo.gs/q4nfHfr

Hopefully you can figure out why this bug happens, and thanks in advance 👍 
Thank you also for adding compatibility with NTM, makes the game much more immersive.

**Comment by Jeryn99** [comment]
Please upload the crash report as a file by dragging and dropping the file into the comments box - I do not like using links like the one provided as the sites can’t often be laggy and remove parts of logs

**Comment by MianReplicate** [comment]
Oh, sorry about that. Here you go:
[crash-2022-10-12_15.51.54-server.txt](https://github.com/Suff99/Weeping-Angels/files/9769147/crash-2022-10-12_15.51.54-server.txt)
