### ISSUE TITLE
Weeping Angels Fabric Server Crash

### ISSUE THREAD

**Issue by Paxx3** [ReallySub/Weeping-Angels-Mod#265]
Hello, i got a problem.

 I have a modpack and i was testing it. I wanted to go to a village (modded village) and so did i.

Well i saw a bunch of angel statues in the snow blocks before i got there and it just randomly crashed the server.

I talked to someone else about this issue. you can understand better from this link : 
 https://github.com/orgs/FabricMC/discussions/2612#discussioncomment-3987259

Here is the latest log: https://pastebin.pl/view/541a34d5

Here is the latest crash log : https://pastebin.pl/view/b1c19373

Thank you.

**Comment by Jeryn99** [comment]
That’s a interesting problem, I’ll try investigate this asap

**Comment by Paxx3** [comment]
Thank you. Please keep me updated when you solve this problem. Have a great day.

**Comment by Paxx3** [comment]
> That’s a interesting problem, I’ll try investigate this asap

Hi man. I hope you are doing well.

  What's the situation? It's been 2 days. Have you solved the problem?

**Comment by Jeryn99** [comment]
I will post updates here as they come

**Comment by Paxx3** [comment]
Thanks.
