### ISSUE TITLE
[Log] Mixin config weeping_angels-common.mixins.json does not specify "minVersion" property

### ISSUE THREAD

**Issue by Lucky-56** [ReallySub/Weeping-Angels-Mod#266]
Just annoying in log

**Forge:** 43.1.47
**Mod Version:** 43.0.8

**Comment by Lucky-56** [comment]
also applies to `Mixin config weeping_angels.mixins.json does not specify "minVersion" property`

**Comment by Jeryn99** [comment]
Merging into https://github.com/Suff99/Weeping-Angels/issues/267 as both are related to the same issue.
