### ISSUE TITLE
Weeping Angels crash.

### ISSUE THREAD

**Issue by OxyV** [ReallySub/Weeping-Angels-Mod#269]
Hello. I have an issue.

Well i have a modpack with 250 mods and i played in a dedicated server, tried to go to nether and the game crashed for no reason.

Here is the latest crash : https://pastebin.pl/view/9a6c9636

Here is the log : https://pastebin.pl/view/ae83b528

The log says the problem is weeping angels, so thats why i posted this issue here
Thank you.

**Comment by Jeryn99** [comment]
The above links have expired? Please provide new ones :)
