### ISSUE TITLE
Minecraft forge 1.18.2 

### ISSUE THREAD

**Issue by alessandriLuca** [ReallySub/Weeping-Angels-Mod#272]
I just got this crash, i guess it is from the weeping angel mod. 
Thanks ;) 

https://pastebin.com/V1tRQJbt

https://pastebin.com/08d3aJJN

**Comment by alessandriLuca** [comment]
Apparently it crashes when i make spawn a creeping angel underground... and actually the server doesnt crash, just the client... doest any of this make sense to you?

**Comment by Jeryn99** [comment]
I'm already fully aware of this issue :)
It's 1.18.2 so it's not a priority yet as all of the 1.19.2 changes are being back ported to support fabric and forge for 1.18.2

**Comment by alessandriLuca** [comment]
oh ok cool ;) so to avoid this issue I should just not make them spawn underground ? Im using incontrol to make them spawn more frequently and with specific rule

**Comment by Jeryn99** [comment]
It's not so much them spawning underground and more that one of the models has issues with rendering, but I am not sure which :)

**Comment by Jeryn99** [comment]
Correction! ModelVAWeepingAngel is the one causing issues

**Comment by alessandriLuca** [comment]
ok great ! So if i recall correctly i can disable it from the config! THanks ;)

**Comment by Jeryn99** [comment]
Until the backport is completed, you will want to add/remove SPARE_TIME to allowedAngelTypes yeah :)

**Comment by alessandriLuca** [comment]
great thanks and good job with everything , love this mod ;)!!
