### ISSUE TITLE
Regeneration mod and weeping angels cause a world gen error [1.18.2]

### ISSUE THREAD

**Issue by SeaCrusher27** [ReallySub/Weeping-Angels-Mod#274]
Hi, im having an issue with the combinations of the two mods and generating a world. This is the crahs report:

> `
> ---- Minecraft Crash Report ----
> // Who set us up the TNT?
> 
> Time: 12/12/22, 5:41 PM
> Description: Exception generating new chunk
> 
> java.lang.IllegalStateException: Feature order cycle found, involved biomes: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:river]=net.minecraft.world.level.biome.Biome@45400d7c}]
> 	at net.minecraft.world.level.biome.BiomeSource.m_186727_(BiomeSource.java:136) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading,pl:accesstransformer:B}
> 	at com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSlicesManager.lambda$onServerAboutToStart$2(ModdedBiomeSlicesManager.java:104) ~[blueprint-1.18.2-5.5.0.jar%2363!/:5.5.0] {re:mixin,re:classloading}
> 	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar%2329!/:?] {}
> 	at net.minecraft.world.level.biome.BiomeSource.m_186733_(BiomeSource.java:258) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:401) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:witherstormmod.mixins.json:IMixinChunkGenerator,pl:mixin:A}
> 	at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.level.ChunkMap.lambda$chunkGenerate$22(ChunkMap.java:728) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
> 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2334!/:?] {}
> 	at net.minecraft.server.level.ChunkMap.lambda$chunkGenerate$24(ChunkMap.java:726) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
> 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
> 	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading}
> 	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading}
> 	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading}
> 	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading}
> 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Server thread
> Stacktrace:
> 	at net.minecraft.world.level.biome.BiomeSource.m_186727_(BiomeSource.java:136) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading,pl:accesstransformer:B}
> 	at com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSlicesManager.lambda$onServerAboutToStart$2(ModdedBiomeSlicesManager.java:104) ~[blueprint-1.18.2-5.5.0.jar%2363!/:5.5.0] {re:mixin,re:classloading}
> 	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar%2329!/:?] {}
> 	at net.minecraft.world.level.biome.BiomeSource.m_186733_(BiomeSource.java:258) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:401) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:witherstormmod.mixins.json:IMixinChunkGenerator,pl:mixin:A}
> 	at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.level.ChunkMap.lambda$chunkGenerate$22(ChunkMap.java:728) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
> 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2334!/:?] {}
> 	at net.minecraft.server.level.ChunkMap.lambda$chunkGenerate$24(ChunkMap.java:726) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
> 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
> 	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading}
> 	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading}
> 	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading}
> 	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading}
> -- Chunk to be generated --
> Details:
> 	Location: -1,-1
> 	Position hash: -1
> 	Generator: net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator@7e14b2cf
> Stacktrace:
> 	at net.minecraft.server.level.ChunkMap.lambda$chunkGenerate$22(ChunkMap.java:728) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
> 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2334!/:?] {}
> 	at net.minecraft.server.level.ChunkMap.lambda$chunkGenerate$24(ChunkMap.java:726) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
> 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
> 	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading}
> 	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading}
> 	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading}
> 	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:classloading}
> 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
> 
> 
> -- Affected level --
> Details:
> 	All players: 0 total; []
> 	Chunk stats: 7921
> 	Level dimension: minecraft:overworld
> 	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
> 	Level time: 0 game time, 0 day time
> 	Level name: New World
> 	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
> 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> 	Known server brands: forge
> 	Level was modded: true
> 	Level storage version: 0x04ABD - Anvil
> Stacktrace:
> 	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:373) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:316) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:blueprint.mixins.json:client.IntegratedServerMixin,pl:mixin:A}
> 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23120!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
> 	at java.lang.Thread.run(Thread.java:833) [?:?] {}
> 
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.18.2
> 	Minecraft Version ID: 1.18.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 17.0.1, Microsoft
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
> 	Memory: 4414052616 bytes (4209 MiB) / 6023020544 bytes (5744 MiB) up to 12884901888 bytes (12288 MiB)
> 	CPUs: 12
> 	Processor Vendor: AuthenticAMD
> 	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
> 	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
> 	Microarchitecture: Zen 2
> 	Frequency (GHz): 3.60
> 	Number of physical packages: 1
> 	Number of physical CPUs: 6
> 	Number of logical CPUs: 12
> 	Graphics card #0 name: spacedesk Graphics Adapter
> 	Graphics card #0 vendor: datronicsoft
> 	Graphics card #0 VRAM (MB): 0.00
> 	Graphics card #0 deviceId: unknown
> 	Graphics card #0 versionInfo: DriverVersion=1.1.352.157
> 	Graphics card #1 name: NVIDIA GeForce RTX 2060
> 	Graphics card #1 vendor: NVIDIA (0x10de)
> 	Graphics card #1 VRAM (MB): 4095.00
> 	Graphics card #1 deviceId: 0x1f08
> 	Graphics card #1 versionInfo: DriverVersion=31.0.15.2756
> 	Graphics card #2 name: vs spacedesk Graphics Adapter
> 	Graphics card #2 vendor: datronicsoft
> 	Graphics card #2 VRAM (MB): 0.00
> 	Graphics card #2 deviceId: unknown
> 	Graphics card #2 versionInfo: DriverVersion=1.1.352.157
> 	Memory slot #0 capacity (MB): 8192.00
> 	Memory slot #0 clockSpeed (GHz): 3.20
> 	Memory slot #0 type: DDR4
> 	Memory slot #1 capacity (MB): 8192.00
> 	Memory slot #1 clockSpeed (GHz): 3.20
> 	Memory slot #1 type: DDR4
> 	Virtual memory max (MB): 31695.80
> 	Virtual memory used (MB): 20950.46
> 	Swap memory total (MB): 15360.00
> 	Swap memory used (MB): 440.91
> 	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m
> 	Server Running: true
> 	Player Count: 0 / 8; []
> 	Data Packs: vanilla, mod:borderlesswindow (incompatible), mod:celestial, mod:weeping_angels (incompatible), mod:jei (incompatible), mod:universalbonemeal (incompatible), mod:obscure_api, mod:hourglass (incompatible), mod:bowinfinityfix (incompatible), mod:mo_potions, mod:clumps (incompatible), mod:xaeroworldmap, mod:controlling (incompatible), mod:portkey (incompatible), mod:citadel (incompatible), mod:sereneseasons (incompatible), mod:myserveriscompatible (incompatible), mod:curioofundying (incompatible), mod:create_confectionery, mod:bedspreads (incompatible), mod:blueprint (incompatible), mod:savage_and_ravage (incompatible), mod:allurement (incompatible), mod:immersive_armors (incompatible), mod:jeresources (incompatible), mod:skinlayers3d (incompatible), mod:forge, mod:scuba_gear (incompatible), mod:selene (incompatible), mod:corpse (incompatible), mod:lapisreserve (incompatible), mod:farmersdelight (incompatible), mod:morevillagers, mod:ob_aquamirae, mod:wildfire_gender, mod:regen (incompatible), mod:loot_journal, mod:jade, mod:obscure_tooltips, mod:another_furniture, mod:personality (incompatible), mod:cloudstorage, mod:cnb (incompatible), mod:flywheel (incompatible), mod:farmersrespite (incompatible), mod:curios (incompatible), mod:patchouli (incompatible), mod:ecologics, mod:xaerominimap, mod:create_sa, mod:camera (incompatible), mod:polymorph (incompatible), mod:backpacked (incompatible), mod:witherstormmod (incompatible), mod:effective_fg (incompatible), mod:universalenchants (incompatible), mod:architectury (incompatible), mod:appleskin (incompatible), mod:mcwfurnitures, mod:extendedflywheels, mod:create, mod:mountedpearl (incompatible), mod:puzzleslib (incompatible), mod:cosmeticarmorreworked (incompatible), mod:geckolib3 (incompatible), mod:creeperoverhaul (incompatible), mod:create_enchantment_industry, mod:createaddition (incompatible)
> 	World Generation: Stable
> 	Type: Integrated Server (map_client.txt)
> 	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
> 	OptiFine Version: OptiFine_1.18.2_HD_U_H9_pre2
> 	OptiFine Build: 20221114-104911
> 	Render Distance Chunks: 8
> 	Mipmaps: 4
> 	Anisotropic Filtering: 1
> 	Antialiasing: 0
> 	Multitexture: false
> 	Shaders: null
> 	OpenGlVersion: 3.2.0 NVIDIA 527.56
> 	OpenGlRenderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
> 	OpenGlVendor: NVIDIA Corporation
> 	CpuCount: 12
> 	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
> 	ModLauncher launch target: forgeclient
> 	ModLauncher naming: srg
> 	ModLauncher services: 
> 		 mixin PLUGINSERVICE 
> 		 eventbus PLUGINSERVICE 
> 		 slf4jfixer PLUGINSERVICE 
> 		 object_holder_definalize PLUGINSERVICE 
> 		 runtime_enum_extender PLUGINSERVICE 
> 		 capability_token_subclass PLUGINSERVICE 
> 		 accesstransformer PLUGINSERVICE 
> 		 runtimedistcleaner PLUGINSERVICE 
> 		 mixin TRANSFORMATIONSERVICE 
> 		 OptiFine TRANSFORMATIONSERVICE 
> 		 fml TRANSFORMATIONSERVICE 
> 	FML Language Providers: 
> 		minecraft@1.0
> 		lowcodefml@null
> 		javafml@null
> 	Mod List: 
> 		BorderlessWindow-1.18-1.4.0.jar                   |Borderless Window             |borderlesswindow              |1.18-1.4.0          |DONE      |Manifest: NOSIGNATURE
> 		celestial_1.18_forge-1.3.3.jar                    |Celestial                     |celestial                     |1.3.3               |DONE      |Manifest: NOSIGNATURE
> 		weeping_angels-1.0.1.jar                          |Weeping Angels                |weeping_angels                |1.0.0               |DONE      |Manifest: NOSIGNATURE
> 		jei-1.18.2-9.7.1.255.jar                          |Just Enough Items             |jei                           |9.7.1.255           |DONE      |Manifest: NOSIGNATURE
> 		UniversalBoneMeal-v3.0.5-1.18.2-Forge.jar         |Universal Bone Meal           |universalbonemeal             |3.0.5               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
> 		obscure_api-9-1.18.jar                            |Obscure API                   |obscure_api                   |9                   |DONE      |Manifest: NOSIGNATURE
> 		hourglass-1.18.2-1.2.1.0.jar                      |Hourglass                     |hourglass                     |1.18.2-1.2.1.0      |DONE      |Manifest: NOSIGNATURE
> 		BowInfinityFix-1.18.x-rv11.jar                    |Bow Infinity Fix              |bowinfinityfix                |1.18.x-rv11         |DONE      |Manifest: NOSIGNATURE
> 		mo_potions-1.4.2-RELEASE+1.18.2MC.jar             |Mo' Potions                   |mo_potions                    |1.4.21.18.2         |DONE      |Manifest: NOSIGNATURE
> 		Clumps-forge-1.18.2-8.0.0+17.jar                  |Clumps                        |clumps                        |8.0.0+17            |DONE      |Manifest: NOSIGNATURE
> 		XaerosWorldMap_1.28.4_Forge_1.18.2.jar            |Xaero's World Map             |xaeroworldmap                 |1.28.4              |DONE      |Manifest: NOSIGNATURE
> 		Controlling-forge-1.18.2-9.0+22.jar               |Controlling                   |controlling                   |9.0+22              |DONE      |Manifest: NOSIGNATURE
> 		portkey-1.18.2-1.12.jar                           |Portkey                       |portkey                       |1.12                |DONE      |Manifest: NOSIGNATURE
> 		citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |DONE      |Manifest: NOSIGNATURE
> 		Serene Seasons-1.18.2-7.0.0.13.jar                |Serene Seasons                |sereneseasons                 |1.18.2-7.0.0.13     |DONE      |Manifest: NOSIGNATURE
> 		MyServerIsCompatible-1.18-1.0.jar                 |MyServerIsCompatible          |myserveriscompatible          |1.0                 |DONE      |Manifest: NOSIGNATURE
> 		curioofundying-forge-1.18-5.3.0.0.jar             |Curio of Undying              |curioofundying                |1.18-5.3.0.0        |DONE      |Manifest: NOSIGNATURE
> 		create-confectionery1.18.2_v1.0.8.jar             |Create Confectionery          |create_confectionery          |1.0.8               |DONE      |Manifest: NOSIGNATURE
> 		bedspreads-forge-1.18.2-5.1.2.0.jar               |Bedspreads                    |bedspreads                    |1.18.2-5.1.2.0      |DONE      |Manifest: NOSIGNATURE
> 		blueprint-1.18.2-5.5.0.jar                        |Blueprint                     |blueprint                     |5.5.0               |DONE      |Manifest: NOSIGNATURE
> 		savage_and_ravage-1.18.2-4.0.0.jar                |Savage & Ravage               |savage_and_ravage             |4.0.0               |DONE      |Manifest: NOSIGNATURE
> 		allurement-1.18.2-2.0.0.jar                       |Allurement                    |allurement                    |2.0.0               |DONE      |Manifest: NOSIGNATURE
> 		immersive_armors-1.5.0+1.18.2.jar                 |Immersive Armors              |immersive_armors              |1.5.0+1.18.2        |DONE      |Manifest: NOSIGNATURE
> 		JustEnoughResources-1.18.2-0.14.1.171.jar         |Just Enough Resources         |jeresources                   |0.14.1.171          |DONE      |Manifest: NOSIGNATURE
> 		3dskinlayers-forge-1.5.2-mc1.18.2.jar             |3dSkinLayers                  |skinlayers3d                  |1.5.2               |DONE      |Manifest: NOSIGNATURE
> 		forge-1.18.2-40.1.85-universal.jar                |Forge                         |forge                         |40.1.85             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
> 		scuba_gear-1.18.2-1.0.4.jar                       |Scuba Gear                    |scuba_gear                    |1.0.4               |DONE      |Manifest: NOSIGNATURE
> 		selene-1.18.2-1.17.9.jar                          |Selene                        |selene                        |1.18.2-1.17.9       |DONE      |Manifest: NOSIGNATURE
> 		corpse-1.18.2-1.0.1.jar                           |Corpse                        |corpse                        |1.18.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
> 		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
> 		lapisreserve-1.0.8F.jar                           |lapisreserve                  |lapisreserve                  |1.0.8F              |DONE      |Manifest: NOSIGNATURE
> 		FarmersDelight-1.18.2-1.2.0.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.2.0        |DONE      |Manifest: NOSIGNATURE
> 		morevillagers-forge-1.18.2-3.3.2.jar              |More Villagers                |morevillagers                 |3.3.2               |DONE      |Manifest: NOSIGNATURE
> 		aquamirae-4.6.api9-1.18.jar                       |Aquamirae                     |ob_aquamirae                  |4.6.api9            |DONE      |Manifest: NOSIGNATURE
> 		[Forge] Wildfire Female Gender Mod-2.9.1.jar      |Wildfire's Female Gender Mod  |wildfire_gender               |2.9.1               |DONE      |Manifest: NOSIGNATURE
> 		regen-40.0.1.jar                                  |Regeneration                  |regen                         |1.0.1               |DONE      |Manifest: NOSIGNATURE
> 		loot_journal-1.1.0-1.18.jar                       |Loot Journal                  |loot_journal                  |1.1.0               |DONE      |Manifest: NOSIGNATURE
> 		Jade-1.18.2-forge-5.2.6.jar                       |Jade                          |jade                          |5.2.6               |DONE      |Manifest: NOSIGNATURE
> 		obscure_tooltips-1.0.api9-1.18.jar                |Obscure Tooltips              |obscure_tooltips              |1.0.api9            |DONE      |Manifest: NOSIGNATURE
> 		another_furniture-forge-1.2.2-1.18.2.jar          |Another Furniture             |another_furniture             |1.2.2-1.18.2        |DONE      |Manifest: NOSIGNATURE
> 		personality-1.18.2-2.0.0.jar                      |Personality                   |personality                   |2.0.0               |DONE      |Manifest: NOSIGNATURE
> 		cloudstorage-1.1.0-1.18.2.jar                     |Cloud Storage                 |cloudstorage                  |1.1.0               |DONE      |Manifest: NOSIGNATURE
> 		CNB-1.18.2-1.4.0.jar                              |Creatures and Beasts          |cnb                           |1.4.0               |DONE      |Manifest: NOSIGNATURE
> 		flywheel-forge-1.18.2-0.6.5.jar                   |Flywheel                      |flywheel                      |0.6.5               |DONE      |Manifest: NOSIGNATURE
> 		FarmersRespite-1.18.2-1.3.0.jar                   |Farmer's Respite              |farmersrespite                |1.18.1-1.3.0        |DONE      |Manifest: NOSIGNATURE
> 		curios-forge-1.18.2-5.0.7.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.1      |DONE      |Manifest: NOSIGNATURE
> 		Patchouli-1.18.2-71.1.jar                         |Patchouli                     |patchouli                     |1.18.2-71.1         |DONE      |Manifest: NOSIGNATURE
> 		ecologics-forge-1.18.2-1.7.10.jar                 |Ecologics                     |ecologics                     |1.7.10              |DONE      |Manifest: NOSIGNATURE
> 		Xaeros_Minimap_22.16.3_Forge_1.18.2.jar           |Xaero's Minimap               |xaerominimap                  |22.16.3             |DONE      |Manifest: NOSIGNATURE
> 		create-stuff-additions1.18.2_v2.0.1c.jar          |Create Stuff & Additions      |create_sa                     |2.0.1               |DONE      |Manifest: NOSIGNATURE
> 		camera-1.18.2-1.0.5.jar                           |Camera Mod                    |camera                        |1.18.2-1.0.5        |DONE      |Manifest: NOSIGNATURE
> 		polymorph-forge-1.18.2-0.46.jar                   |Polymorph                     |polymorph                     |1.18.2-0.46         |DONE      |Manifest: NOSIGNATURE
> 		backpacked-2.1.10-1.18.2.jar                      |Backpacked                    |backpacked                    |2.1.10              |DONE      |Manifest: NOSIGNATURE
> 		witherstormmod-1.18.2-2.1.1.jar                   |Cracker's Wither Storm Mod    |witherstormmod                |2.1.1               |DONE      |Manifest: NOSIGNATURE
> 		effective_fg-1.2.4.jar                            |Effective (Forge)             |effective_fg                  |1.2.4               |DONE      |Manifest: NOSIGNATURE
> 		UniversalEnchants-v3.0.6-1.18.2-Forge.jar         |Universal Enchants            |universalenchants             |3.0.6               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
> 		architectury-4.10.88-forge.jar                    |Architectury                  |architectury                  |4.10.88             |DONE      |Manifest: NOSIGNATURE
> 		appleskin-forge-mc1.18.2-2.4.1.jar                |AppleSkin                     |appleskin                     |2.4.1+mc1.18.2      |DONE      |Manifest: NOSIGNATURE
> 		mcw-furniture-3.0.2-mc1.18.2.jar                  |Macaw's Furniture             |mcwfurnitures                 |3.0.2               |DONE      |Manifest: NOSIGNATURE
> 		extendedflywheels-1.2.4-1.18.2-0.5.e.jar          |Extended Flywheels            |extendedflywheels             |1.2.4-1.18.2-0.5.e  |DONE      |Manifest: NOSIGNATURE
> 		create-1.18.2-0.5.0.e.jar                         |Create                        |create                        |0.5.0.e             |DONE      |Manifest: NOSIGNATURE
> 		mountedpearl-1.18-1.0.0.jar                       |Mounted Pearl                 |mountedpearl                  |1.18-1.0.0          |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
> 		PuzzlesLib-v3.3.5-1.18.2-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.3.5               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
> 		CosmeticArmorReworked-1.18.2-v2a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.18.2-v2a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
> 		geckolib-forge-1.18-3.0.56.jar                    |GeckoLib                      |geckolib3                     |3.0.56              |DONE      |Manifest: NOSIGNATURE
> 		creeperoverhaul-1.3.1-forge.jar                   |Creeper Overhaul              |creeperoverhaul               |1.3.1               |DONE      |Manifest: NOSIGNATURE
> 		create_enchantment_industry-1.18.2-for-create-0.5.|Create Enchantment Industry   |create_enchantment_industry   |1.1.6               |DONE      |Manifest: NOSIGNATURE
> 		createaddition-1.18.2-20221122a.jar               |Create Crafts & Additions     |createaddition                |1.18.2-20221122a    |DONE      |Manifest: NOSIGNATURE
> 	Crash Report UUID: 80bf687b-975f-47cf-9cd6-aa30c9829bd3
> 	Flywheel Backend: GL33 Instanced Arrays
> 	FML: 40.1
> 	Forge: net.minecraftforge:40.1.85
> `

Ive searched it up and think it is something to do with the order of structure generation being differnet in the two mods. This may not be the cause but thought it may help

**Comment by Jeryn99** [comment]
In future, crash reports should be uploaded via drag and drop as files so that the issue is more concise 

But, does it happen with the other mod on its own?

**Comment by SeaCrusher27** [comment]
Both work individually but when put together they crash on worldgen

**Comment by Jeryn99** [comment]
I'll look into it
