### ISSUE TITLE
Angels stealing problem [Forge 1.19.2]

### ISSUE THREAD

**Issue by MistWatcher** [ReallySub/Weeping-Angels-Mod#275]
Version 43.0.9 forge - Angel steal any weapon from the first hotbar slot, but if you kill that angel, it will drop the best pickaxe from your inventory (duplicate it), not the weapon.
    It would be cool to add possibility to disable stealing in configs.  I was upset when I just lose great sword :(

**Comment by Jeryn99** [comment]
This was already fixed in https://github.com/Suff99/Weeping-Angels/commit/d5ceb70f8039c81e9fb417f0c6d5fa6bf3d454a6
Just not released yet
