### ISSUE TITLE
how can i turn off teleporting?

### ISSUE THREAD

**Issue by Surpos0** [ReallySub/Weeping-Angels-Mod#276]
hi i want to play with this mod but without angels teleporting me between dimensions. 
and it I have trouble to do so with config cuz it says that i can set its min rate to 1% not 0%

**Comment by Jeryn99** [comment]
Minecraft version?

**Comment by Surpos0** [comment]
1.19.2 fabric latest version of mod

**Comment by Jeryn99** [comment]
Seems the toggle option was removed when we went over to Fabric, I will add one for the next update
