### ISSUE TITLE
can't kill angels in the nether fabric 1.19.2

### ISSUE THREAD

**Issue by kaidelregno** [ReallySub/Weeping-Angels-Mod#277]

**Comment by Jeryn99** [comment]
are you using the correct tool for the angels variant?

**Comment by kaidelregno** [comment]
Ok listen

No nether - can kill angels with pick

Nether - cannot kill angels with pick

Back to overworld - no longer can kill angels with pick

Diamond pick all times

Wym variant

**Comment by Jeryn99** [comment]
I cannot re-create this, perhaps you have another mod installed that's stopping it?
