### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by LatentDesire1** [ReallySub/Weeping-Angels-Mod#281]
https://paste.ee/p/U9jdT

**Comment by Rogenar** [comment]
I am having the same problem. Weeping Angels - Fabric] - Game crashes in v44.0.0.
[crash-2023-04-03_18.46.21-client.txt](https://github.com/Suff99/Weeping-Angels/files/11140084/crash-2023-04-03_18.46.21-client.txt)
[latest.log](https://github.com/Suff99/Weeping-Angels/files/11140085/latest.log)
[rei.log](https://github.com/Suff99/Weeping-Angels/files/11140086/rei.log)
[rei-issues.log](https://github.com/Suff99/Weeping-Angels/files/11140087/rei-issues.log)

**Comment by Jeryn99** [comment]
@Rogenar Not you're not - the submitted issue is a worldgen issue caused by another mod, your crash is caused by a bad resourcelocation, I need to ask questions about your install - please make your own issue as this one will be closed due to being invalid.
