### ISSUE TITLE
If the user's language uses non-standard characters, the game crashes

### ISSUE THREAD

**Issue by Rogenar** [ReallySub/Weeping-Angels-Mod#282]
Weeping Angels - Fabric] - Game crashes in v44.0.0.
[rei-issues.log](https://github.com/Suff99/Weeping-Angels/files/11140591/rei-issues.log)
[rei.log](https://github.com/Suff99/Weeping-Angels/files/11140592/rei.log)
[latest.log](https://github.com/Suff99/Weeping-Angels/files/11140593/latest.log)
[crash-2023-04-03_18.46.21-client.txt](https://github.com/Suff99/Weeping-Angels/files/11140594/crash-2023-04-03_18.46.21-client.txt)

**Comment by Jeryn99** [comment]
And this is 1.19.3?

**Comment by Rogenar** [comment]
1.20.1

**Comment by Jeryn99** [comment]
Crash report indicates 1.19.3?

**Comment by Rogenar** [comment]
I shared this edition months ago. Now I'm playing fabric version 1.20.1 and I'm facing the game crash again. I guess the game crashes when you get close enough to the weeping angel.
[crash-2023-06-29_22.34.54-client.txt](https://github.com/Suff99/Weeping-Angels/files/11909808/crash-2023-06-29_22.34.54-client.txt)
[latest.log](https://github.com/Suff99/Weeping-Angels/files/11909810/latest.log)
[rei.log](https://github.com/Suff99/Weeping-Angels/files/11909811/rei.log)
[rei-issues.log](https://github.com/Suff99/Weeping-Angels/files/11909813/rei-issues.log)

**Comment by Jeryn99** [comment]
easy fix I think, I assume you do not play the game in english?

**Comment by Rogenar** [comment]
Yes, I am playing the game in Turkish.

**Comment by Jeryn99** [comment]
yeah its just a encoding thing based on your pcs language, I will sort it in all versions asap

**Comment by Rogenar** [comment]
Ok then. I will be waiting for the new corrected version.

**Comment by Jeryn99** [comment]
Fixed
