### ISSUE TITLE
Teleported and lost my base

### ISSUE THREAD

**Issue by Doyle63** [ReallySub/Weeping-Angels-Mod#285]
So I was teleported by an angel in the nether to the over world and when it shows where my base is it's a completely newly generated terrain

**Comment by CommandrMoose** [comment]
There's not much we can do with this ticket.

Please answer the following if you wish for us to help you further:

Game Version:
Fabric or Forge:
Weeping Angels version:

Are you playing with other mods?:

**Comment by Jeryn99** [comment]
I am closing this until you provide more information in the comments
