### ISSUE TITLE
1.19.2 problem, big lag problem

### ISSUE THREAD

**Issue by SpartanDraco** [ReallySub/Weeping-Angels-Mod#288]
In 1.19.2 when an angel appears and moves, it starts to slow down the server, either a single player or a lan, there are peaks of 300 ms when the angel moves.

**Comment by LegitGamer1017** [comment]
Same issue here. I'm using forge 43.2.14, with Weeping Angels v43.0.9. The lag is so bad when they are trying to move/teleport, I had to manually disable their spawns because players found it so frustrating to play against. 

https://spark.lucko.me/r5dUGOf1dR

Here is a link to a spark profiler.

**Comment by Jeryn99** [comment]
> Same issue here. I'm using forge 43.2.14, with Weeping Angels v43.0.9. The lag is so bad when they are trying to move/teleport, I had to manually disable their spawns because players found it so frustrating to play against.
> 
> https://spark.lucko.me/r5dUGOf1dR
> 
> Here is a link to a spark profiler.

Are you sure you linked the correct spark report? The entity count summary doesn't list angels

**Comment by LegitGamer1017** [comment]
Pretty sure that's the correct one. I was looking through the server thread and went to ServerLevel.tick() --> guardEntityTick() --> OnTickNonPassenger() --> WeepingAngel.tick() --> Teleporter.performTeleport(). Weird that it doesn't show up in the entity count summary but yeah. 

During the lag spike, there was only 1-2 Weeping Angels as well, not like 10+. 

![image](https://github.com/Suff99/Weeping-Angels/assets/46847496/d3400645-830e-4cb4-ae65-7f942e68138e)

**Comment by Jeryn99** [comment]
Perhaps I’m just unfamiliar with sparks ui these days 

There does seem to be a bug where Angels are teleporting each other and other random entities which would definitely cause a lag spike - I will write something to rectify this and upload a jar to this issue and see if it fixes your lag?

**Comment by LegitGamer1017** [comment]
Sure, thank you!

**Comment by SpartanDraco** [comment]
I also noticed that in the version prior to the latest version in 1.19.2 they do not spawn directly, but the lag still exists.

**Comment by SpartanDraco** [comment]
Also note, that unlike the companion I tested it with all versions of forge 43.x.xx

**Comment by Jeryn99** [comment]
Fixed for 1.20, I will backport soon
