### ISSUE TITLE
They spawn way too much in the nether[1.19.3]

### ISSUE THREAD

**Issue by Erik9996** [ReallySub/Weeping-Angels-Mod#289]
In the nether, sometimes up to 12 spawn all at once and surround you. even if you manage to kill all of them it will only take about a minute until 3 more spawn. This makes the nether pretty much unplayable, especially when you have to factor that there's other mobs that wanna attack you at the same time while these things constantly spawn about every minute

**Comment by Jeryn99** [comment]
Moving Spawn issues to this issue, please track that https://github.com/Suff99/Weeping-Angels/issues/316
