### ISSUE TITLE
Still no option to turn off teleporting | fabric 1.20.1

### ISSUE THREAD

**Issue by Surpos0** [ReallySub/Weeping-Angels-Mod#290]
In 1.19 there was no config option to turn off teleporting into other dimensions, and this is still problem in 1.20.1

[teleporting]
	#Determines the range that a player can be teleported from their current location
	#Range: > 1
	teleport_range = 400
	#Determines the chance a player will be teleported
	#Range: 1 ~ 100
	teleport_chance = 1
	#A list of Dimensions that angels cannot teleport players to
	banned_dimensions = ["minecraft:the_end"]

**Comment by Jeryn99** [comment]
Added it for the next 1.20 version
