### ISSUE TITLE
1.19.2 Spawn Issue in code

### ISSUE THREAD

**Issue by Spider4896** [ReallySub/Weeping-Angels-Mod#293]
Hi, 
Noticed that in the code for the angels to spawn in catacombs, its written as, 
Current:  weeping-angels:weeping_angel

I changed it to, 
New:  weeping_angels:weeping_angel

This allowed them to start spawning in their catacombs for me.
Unsure if this is a problem or intended but thought I bring it up.

**Comment by Jeryn99** [comment]
Which file are you referring to?

**Comment by Spider4896** [comment]
Fabric
43.0.9

**Comment by Spider4896** [comment]
Weeping-Angels-43.0.9-fabric.jar\data\weeping_angels\worldgen\structure\catacombs.json

{
  "type": "minecraft:jigsaw",
  "start_pool": "weeping_angels:catacombs/catacombs",
  "size": 5,
  "max_distance_from_center": 80,
  "biomes": "#weeping_angels:has_structure/catacombs",
  "step": "underground_structures",
  "start_height": {
    "absolute": 0
  },
  "use_expansion_hack": false,
  "spawn_overrides": {
    "monster": {
      "bounding_box": "full",
      "spawns": [
        {
          "type": "weeping-angels:weeping_angel",
          "weight": 30,
          "minCount": 1,
          "maxCount": 4
        }
      ]
    }
  }
}

**Comment by Jeryn99** [comment]
No, which file did you edit?

Edit: Thanks
