### ISSUE TITLE
Music Discs don't work. 1.20.1 Forge

### ISSUE THREAD

**Issue by Duxtorm** [ReallySub/Weeping-Angels-Mod#297]
Hey, I'm using the Weeping Angels 46.0.1 on Forge 47.1.39 and the discs just don't work..
You right click a jukebox with one and the disc just disappears with no music.

**Comment by Jeryn99** [comment]
Does it operate like a standard Disc item, just with no sound?

**Comment by Duxtorm** [comment]
> Does it operate like a standard Disc item, just with no sound?

No, the disc is destroyed.
It does not enter of leave the jukebox, it just.. ceases to exist xnx

**Comment by Jeryn99** [comment]
Is this on Forge or Fabric?

**Comment by aujwalkin** [comment]
same issue 1.20.1 fabric
