### ISSUE TITLE
Angels stealing items from my hotbar, it gets replaced with a pickaxe, 1.19.2

### ISSUE THREAD

**Issue by leandr980** [ReallySub/Weeping-Angels-Mod#299]
Whenever an angel steals one of my items on my hotbar and teleports me, once i find the angel that stole my item i can see it gets replaced with whatever pickaxe I had on the hotbar

In the end my stolen item is gone and i get a dupped pickaxe

**Comment by Balofoide** [comment]
Same happening to me

**Comment by LiekosSilver** [comment]
Happened on a server also. had 4 reports of it to.  2 from my self, 2 from others on the server.

**Comment by Kindredphoenix** [comment]
same happening to me as well. On my server they always steal our swords and i cant find a way to disable that feature in the config files. Does anybody have a fix?

**Comment by Jeryn99** [comment]
> same happening to me as well. On my server they always steal our swords and i cant find a way to disable that feature in the config files. Does anybody have a fix?

Your query has been answered in https://github.com/Suff99/Weeping-Angels/issues/318 @Kindredphoenix 

@Balofoide @leandr980 This was fixed a year ago, I just never had a reason to release the update for such a small code change, I will release it very soon

**Comment by Kindredphoenix** [comment]
Let me know when its released cause i do need it fixed soon

**Comment by Tom-atoes** [comment]
> @Balofoide @leandr980 This was fixed a year ago, I just never had a reason to release the update for such a small code change, I will release it very soon

Can you release this patch soon? This is an incredibly annoying bug especially in the nether.

**Comment by 1kili2** [comment]
from my experience of the last 3 VERY frustrating days trying to build a nether ice boat rail i have noticed that they seem to specifically steal the first item in your hotbar, and they dont necesarily turn it into a pickaxe ive also had them turn the item into a full stack of torches, this seems to even occur occasionally when there is no item in the first slot.

Hope that update gets released soon cause i love this mod but having a maxed out tinkers sword get turned into a spare diamond pickaxe wasn't very fun, in the meanwhile i guess i will have to learn how to make a datapack
