### ISSUE TITLE
Create & Blue Skies Incompatibility [Forge - 1.18.2]

### ISSUE THREAD

**Issue by LauftaProufundus** [ReallySub/Weeping-Angels-Mod#300]
I'm working on a 1.18.2 modpack that would've included this mod, but unfortunately it causes a lot of issues with two major mods in the pack.

1. Create undergoes _Loading issues,_ stating it couldn't load properly when the game starts up.
2. Blue Skies undergoes _Datapack issues_ when attempting to create a new world, requesting the issue be resolved in the main menu or for the world to be created in "Safe Mode" which ends up repeating the cycle after freezing.

The primary issue may be the "WAFeatures" part of the mod, according to Logs. The lovely people over on the Modding Discord of Blue Skies pointed it out since I'm not really an experienced modder, and removing said mod resolved the issue.

**Comment by Jeryn99** [comment]
Im aware of this issue, I just forgot about it with new Minecraft versions dropping 

I'll fix it this week

**Comment by Jeryn99** [comment]
Could I have a log?
