### ISSUE TITLE
No spawning Fabric 1.20.1 - v46.0.1

### ISSUE THREAD

**Issue by NerdRot** [ReallySub/Weeping-Angels-Mod#301]
I've generated a few worlds on hard mode and teleported to catacombs and haven't seen any angels yet.
They spawn fine with the spawn item but it appears they wouldn't exist in a normal survival setting.

**Comment by Jeryn99** [comment]
Moving Spawn issues to this issue, please track that https://github.com/Suff99/Weeping-Angels/issues/316
