### ISSUE TITLE
It destroys the game Fabric 1.20.1

### ISSUE THREAD

**Issue by makumaku1974** [ReallySub/Weeping-Angels-Mod#302]
I really want this mod to be part with my modpack since it's fun. 

Here is the logs and crash reports.

[latest.log](https://github.com/Suff99/Weeping-Angels/files/12342657/latest.log)

[crash-2023-08-15_16.56.31-client.txt](https://github.com/Suff99/Weeping-Angels/files/12342659/crash-2023-08-15_16.56.31-client.txt)

I could not identify the problem but due to the complexity of java it is certainly a two mods conflicting with fabric.

**Comment by Jeryn99** [comment]
This crash has nothing to do with Weeping Angels 

```
net.mehvahdjukaar.moonlight.api.platform.fabric.RegHelperImpl.lambda$addItemsToTabsRegistration$12(RegHelperImpl.java:220)

```
Appears to be caused by something called moonlight

**Comment by makumaku1974** [comment]
so i should update it or remove it?

**Comment by Jeryn99** [comment]
Attempt to load the game without the offending mod

**Comment by makumaku1974** [comment]
ill check again if it works

**Comment by makumaku1974** [comment]
> Attempt to load the game without the offending mod

Does your mod conflict with Supplementaries? coz i swear it works well though because Supplementaries mod uses moonlight lib

**Comment by Jeryn99** [comment]
You will need to try and see, I do not play Minecraft so I do not know what ever mod is and does

**Comment by makumaku1974** [comment]
i think i found a bug. looking down doesn't make the angel move. only up, back, left, and right.

**Comment by makumaku1974** [comment]
and also the coffin block gives xray below the ground.

**Comment by Jeryn99** [comment]
These issues are not relevant to the one you have reported.
