### ISSUE TITLE
[1.20.1 Forge] Crash upon checking donators

### ISSUE THREAD

**Issue by MrKashew** [ReallySub/Weeping-Angels-Mod#305]
[crash-2023-08-20_17.00.05-client.txt](https://github.com/Suff99/Weeping-Angels/files/12389448/crash-2023-08-20_17.00.05-client.txt)

**Comment by Jeryn99** [comment]
Should now be resolved, no need to redownload - backend went through some changes earlier and it seems I overlooked name updates
