### ISSUE TITLE
The game crashed whilst rendering overlay

### ISSUE THREAD

**Issue by mikoooo12** [ReallySub/Weeping-Angels-Mod#306]
The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.ModLoadingException: Weeping Angels (weeping_angels) encountered an error during the done event phase
This happened after trying to load a modpack with weeping angels that gave this error:
https://bytebin.lucko.me/9692cg2c8S
first line: net.minecraftforge.fml.ModLoadingException: Weeping Angels (weeping_angels) encountered an error during the done event phase §7java.lang.UnsupportedOperationException: JsonNull
![image](https://github.com/Suff99/Weeping-Angels/assets/73336656/92beb0db-6360-4335-9581-e151121b0a29)
after that i tried to launch the game without any other mods other than weeping angel which then it gave this error:
[latest.log](https://github.com/Suff99/Weeping-Angels/files/12391305/latest.log)

**Comment by Jeryn99** [comment]
Resolved https://github.com/Suff99/Weeping-Angels/issues/306
