### ISSUE TITLE
"java.lang.UnsupportedOperationException: JsonNull" [Forge 1.19.3]

### ISSUE THREAD

**Issue by Zelta-Deluxe** [ReallySub/Weeping-Angels-Mod#307]
My game crashes randomly and the log seems to indicate problems with Weeping Angels. Error says something about "JsonNull", which I'll suppose that has something to do with configuration files, maybe? This happens mostly in daytime so, maybe it is related to spawning?

[latest.log](https://github.com/Suff99/Weeping-Angels/files/12394135/latest.log)

**Comment by Jeryn99** [comment]
Resolved https://github.com/Suff99/Weeping-Angels/issues/306
