### ISSUE TITLE
[1.19.3] Can't change the pose, expression or look of a statue.

### ISSUE THREAD

**Issue by ShatteredXeno** [ReallySub/Weeping-Angels-Mod#308]
There is no confirm or exit button in the menu to make the changes, and the the statue doesn't reflect the image in the menu. The only thing that change are missing body parts.

**Comment by ginsm** [comment]
I've managed to find a way to confirm saving the pose (at least on 1.20.1).. press `tab` until none of the buttons are selected and then press `enter`.

**Comment by Jeryn99** [comment]
Thanks for reporting, will investigate soon

**Comment by ZiLenTz** [comment]
> I've managed to find a way to confirm saving the pose (at least on 1.20.1).. press `tab` until none of the buttons are selected and then press `enter`.

Gonna try this!
Same issue here on 1.20.1, Fabric 0.14.24, v46.0.1
