### ISSUE TITLE
 bad teleportation | wither storm mod 1.20.1 + Weeping Angels 1.20.1

### ISSUE THREAD

**Issue by JoseBarh** [ReallySub/Weeping-Angels-Mod#310]
Description of Weeping Angels: Weeping Angels will teleport you to a random place in a random dimension, and this includes other mods/datapack dimensions!*

When the wither storm is level 7 the angel sends you to his dimension outside the map (on top of everything)

**Comment by Jeryn99** [comment]
god damn nether based dimensions
