### ISSUE TITLE
Deeper darker spawning issue

### ISSUE THREAD

**Issue by XeeXeeVR** [ReallySub/Weeping-Angels-Mod#311]
As for any other nether-like dimension it spawns me on top of the bedrock roof of the deeper and darker dimension.  I'm aware of the method of excluding dimensions however I can't seem to find the exact tag to add for the deeper darker dimension.  This is on forge 1.20.1 but I do see a number of people having the same issue all over the place

I don't know anything about modding but if possible a solution could be to not allow the teleport to put you on bedrock that is above sea level or something along those lines.  So say the bedrock is 150 blocks up in the world the game registers it as a bedrock roof and finds a place below it that won't suffocate you and places you there instead

**Comment by ginsm** [comment]
In terms of blacklisting a dimension, an easy way to find out the names of the dimensions you have installed is to type `/execute in ` and auto complete should show you the tags for any dimensions you have installed. In the case of deeper and darker, it should be `deeperdarker:otherside` (at least it is on Fabric).

But yeah, finding a safe spot would be ideal. :P

**Comment by Heliart01** [comment]
> In terms of blacklisting a dimension, an easy way to find out the names of the dimensions you have installed is to type `/execute in ` and auto complete should show you the tags for any dimensions you have installed. In the case of deeper and darker, it should be `deeperdarker:otherside` (at least it is on Fabric).
> 
> But yeah, finding a safe spot would be ideal. :P

Hello, could it be possible for you to show me the correct way to blacklist a dimension please? no matter how i try to do it it doesn't work i've tried multiple ways to write it like banned_dimensions = ["minecraft:the_end,deeperdarker:otherside"] but i haven't found one that work yet

**Comment by Heliart01** [comment]
Ok nvm i found it, but if someone else come here for the same issue, the correct way to write it is :  

banned_dimensions = ["minecraft:the_end", "deeperdarker:otherside"]
