### ISSUE TITLE
[1.20.1 Forge] Client Crash - Donator function

### ISSUE THREAD

**Issue by MrKashew** [ReallySub/Weeping-Angels-Mod#312]
[crash-2023-10-02_21.39.06-client.txt](https://github.com/Suff99/Weeping-Angels/files/12788606/crash-2023-10-02_21.39.06-client.txt)

**Comment by MrKashew** [comment]
crash above was in world, similar crash on new world upon joining server

**Comment by Jeryn99** [comment]
Fixed, was some backend changes once more

**Comment by MrKashew** [comment]
is it possible to have client mod fallback instead of crash when backend fails to retrieve donators?
I don't see get donators being essential in terms of crashing client

**Comment by Jeryn99** [comment]
I don't maliciously crash it, but there should be some fallback that I will add shortly
