### ISSUE TITLE
1.19.2 quilt client crash

### ISSUE THREAD

**Issue by SubayAdamm** [ReallySub/Weeping-Angels-Mod#315]
[crash-2023-10-12_22.16.50-client.txt](https://github.com/Suff99/Weeping-Angels/files/12886372/crash-2023-10-12_22.16.50-client.txt)
crash report above

my friend and i have been playing together with the essential mod installed, another friend of mine had the same error months ago when we tried to play with 5-6 people

my friend has minecraft in english as ive seen on another issue and thought it could be because of the language or something

**Comment by Jeryn99** [comment]
Monitor this issue: https://github.com/Suff99/Weeping-Angels/issues/315

**Comment by SubayAdamm** [comment]
yeah its because of the computers language, thanks anyway
