### ISSUE TITLE
Angels keep stealing tools/weapons.

### ISSUE THREAD

**Issue by Kindredphoenix** [ReallySub/Weeping-Angels-Mod#318]
This mod is active on my 1.19.2 server but the angels keep taking our weapons/tools when ever they teleport us. Is there a way to disable this feature in the config?

**Comment by Jeryn99** [comment]
Create a data pack that removes all the items from ``weeping_angels:stealable_items``

**Comment by ghost** [comment]
I can add that they do still steal your sword, but only when you have a pickaxe. It does not have to teleport you for it to happen, you only have to take damage. 
When you break her, she drops a pickaxe, not the weapon she stole.

Edit: I just noticed that my modpack doesn't use the latest version of this mod as it's still on minecraft 1.19.2, this means I might be wrong on whether it still occurs.

**Comment by ghost** [comment]
After checking in minecraft 1.10.1 it works as intended. I know you can't possibly do this for every individual minecraft version. Is it possible to roll out a general fix for all versions? Like a script that just removes one feature?
