### ISSUE TITLE
since the last issue was closed before it was resolved

### ISSUE THREAD

**Issue by Carnage109** [ReallySub/Weeping-Angels-Mod#320]
I installed configure and changed the spawn rate from 8 to 200 and nothing still spawns and the closest catacombs or whatever it is, is 25,000+ blocks away, and other advice?

**Comment by Carnage109** [comment]
i am using 1.19.2 forge and have config and it makes no difference, some help would be appreciated

**Comment by Jeryn99** [comment]
You need to restart your world/game 

If you've done that, you're reporting a existing bug or did not configure it correctly - only vanilla biomes are supported by default, you need to make a data pack at the current moment in time for other mods biomes
