### ISSUE TITLE
1.19.2 Forge Angels don't spawn naturally

### ISSUE THREAD

**Issue by AWhopping0XP** [ReallySub/Weeping-Angels-Mod#322]
Im very new to modding so it may be an obvious issue but I havent been able to find the answer, but I can spawn the angels manually, but I can't get them to spawn on their own even in the catacombs. I have a config menu but it doesnt have anything about spawn rates.

**Comment by Jeryn99** [comment]
Moving Spawn issues to this issue, please track that https://github.com/Suff99/Weeping-Angels/issues/316
