### ISSUE TITLE
Minecraft 1.19.3 Forge not able to config mod

### ISSUE THREAD

**Issue by Vivianrosee** [ReallySub/Weeping-Angels-Mod#325]
Config button lacks functionality. I've reinstalled abut 3 times now. Hoping it was just overlooked and was a feature that was forgotten to add.

**Comment by Jeryn99** [comment]
Config button?

**Comment by Jeryn99** [comment]
Config screens are no longer added natively by forge, this is why the button does not function. Most mods, including this one require you to install a mod such as configured in order to make config changes

https://www.curseforge.com/minecraft/mc-mods/configured
