### ISSUE TITLE
[Forge Vivecraft 1.20.1] Angels only tracking the crosshair/hand. Moving when staring right at them

### ISSUE THREAD

**Issue by Dinoavatar** [ReallySub/Weeping-Angels-Mod#326]
Tried playing this mod using Vivecraft Forge 1.20.1, and the angels didn't really mind me looking right at them as long as I had my hands behind my back. They seemed to only track the crosshair/my right hand, and not my head. Saw on your Discord that this issue's popped up a few times, but also that any update to fix it was from a couple years ago.

**Comment by Jeryn99** [comment]
You'll need this when it updates https://www.curseforge.com/minecraft/mc-mods/vivecraft-forge-extensions

**Comment by Dinoavatar** [comment]
Unfortunately it says in the description that Forge Extensions itself won't update, as the features were rolled into the main mod.

**Comment by Jeryn99** [comment]
FUCK

**Comment by Jeryn99** [comment]
I will look into it.

**Comment by Dinoavatar** [comment]
Thank you!

**Comment by Jeryn99** [comment]
Keep track of https://github.com/Suff99/Weeping-Angels/pull/333

**Comment by Jeryn99** [comment]
Should be fixed now!

**Comment by Jeryn99** [comment]
Confirmed fixed 
![2024-05-24_13 19 29](https://github.com/Jeryn99/Weeping-Angels/assets/36424503/717a3e0d-a1d3-4594-bbc5-5ff074ac9c57)
