### ISSUE TITLE
Angels stop taking damage. [Weeping-Angels v.46.0.1, forge v.47.2.0, Minecraft v.1.20.1]

### ISSUE THREAD

**Issue by sivka12** [ReallySub/Weeping-Angels-Mod#329]
On our server, angels are immortal. They don't take damage even when they're motionless. When we turn on the server, angels can be killed, but after a while the angels stop taking damage, and all damage is returned to the player.

**Comment by Jeryn99** [comment]
Hello,
Please ensure you are only attaching the Weeping Angels with the relevant Pickaxe following Minecrafts mining rules, for example redstone blocks require a iron pickaxe etc - there is one exception to this, where the dirt angel needs a shovel

Thanks

**Comment by sivka12** [comment]
I checked again. There are about 82 angels in Nether, an angel takes damage when hit, but then stops taking damage. The same angel, the same tool - a pickaxe. Maybe the angels are not working correctly in Nether?

**Comment by Jeryn99** [comment]
Can you make a video of the issue?

**Comment by sivka12** [comment]
https://github.com/Suff99/Weeping-Angels/assets/35068896/c4b31a62-06e6-4865-a094-0881d7981f13
Edit: The video doesn't work for some reason, I uploaded it to YouTube https://youtu.be/CoU2n1LJXBQ
I spawned an angel and broke it. After about 10 attempts, an immortal angel got caught. Sometimes they take damage before becoming immortal.

We also have other mods, maybe some of them conflict with Angels:
azurelib-forge-1.20.1-1.0.15
Bookshelf-Forge-1.20.1-20.1.6
chisels-and-bits-forge-1.4.145-1.20.1
curios-forge-5.2.0-beta.3+1.20.1
doppelganger_V5_1.20.1
EnchantmentDescriptions-Forge-1.20.1-17.0.8
EnhancedAI-2.0.3-mc1.20.1
from-another-world-1.2A.1-forge-1.20.1
FromAnotherLibrary-forge-1.20.1-1.0.2
geckolib-forge-1.20.1-4.2.2
gravestone-1.20.1-1.0.5
hourglass-1.20-1.2.1.1
InsaneLib-1.12.1-mc1.20.1
inventorysorter-1.20.1-23.0.1
jei-1.20.1-forge-15.2.0.27
John_Mod_Reborn_1.0.4_mc1.20.1
mobhealthbar-forge-1.20.x-2.3.0
modonomicon-1.20.1-forge-1.40.0
occultism-1.20.1-1.89.1
preview_OptiFine_1.20.1_HD_U_I6_pre6
SmartBrainLib-neoforge-1.20.1-1.12
sons-of-sins-1.20.1-2.0.5
the+man+1.20.1+alpha+0.2.1a
Weeping-Angels-46.0.1-forge

**Comment by sivka12** [comment]
I have read the closed topics. People also have problems with an angel in dirt. The angel does not take damage even with a shovel. You can see it on my video. In the survival game, this is very common, especially in Nether. I don't know what to do. The mod is interesting, but apparently I'll have to disable it.
