### ISSUE TITLE
Changing Banned Dimensions Causes Crash [ 1.19.2 ]

### ISSUE THREAD

**Issue by PabloWasNot** [ReallySub/Weeping-Angels-Mod#331]
Refer to the title mostly. Had an idea to create a custom dimension, but I first wanted to see how easy it was to change the angel's Config to make it so every dimension was blacklisted besides one ( The nether ) therefore if it worked as I thought it would teleport me to the nether no issues, and after Debugging I spotted that after getting grabbed the game glitched with a crash report. This occurred right as they grabbed me and froze the game for a second.

**_THE CRASH REPORT IS NOT THE ISSUE BUT WAS APPART OF IT I ATTEMPTED TO GET HELP FOR THIS GLITCH BUT WAS TOLD FAULTY MOD ISSUES SO I POSTED IT HERE_**

https://gnomebot.dev/paste/1183939204099612742
The Link for the Crash Log

And the code that I changed ( Teleport Section )
I changed the banned Dimensions Section 
[teleporting]
	#Determines the range that a player can be teleported from their current location
	#Range: > 1
	teleport_range = 400
	#Determines the chance a player will be teleported
	#Range: 1 ~ 100
	teleport_chance = 100
	#A list of Dimensions that angels cannot teleport players to
	**_banned_dimensions = ["minecraft:the_end", "minecraft:toverworld"]_**

**Comment by Jeryn99** [comment]
Yep. that's on me, I will have a look

**Comment by Jeryn99** [comment]
Fixed for next 1.19.2 version

**Comment by PabloWasNot** [comment]
Thank you!
