### ISSUE TITLE
Angel dropped torches instead of pickaxe

### ISSUE THREAD

**Issue by Izanagi007** [ReallySub/Weeping-Angels-Mod#332]
Hey there! Just here to report a weird occurrence that happened to me today while playing with the mod. This occurred in version 1.19.2, latest update 43.0.9 on forge.

So while I was adventuring and testing if the angel would teleport me to any of the added banned dimensions (It all worked fine! I did not get teleported to any dimension), a weeping angel stole my pickaxe, which was nothing new, but instead of having it displayed on it's head, it was holding torches. On my inventory, I did had around 28 torches, but for some reason they where still there, even though the angel clearly had them; I didn't put much thought to it and defeated it, only for it to drop the same number of torches I had in hand and no pickaxe; long story short, through the session this happened a few more times, losing a few iron picks and getting 3-4 stacks of torches. 

I tried to look into the files to turn off the item stealing, which I thought it would be a nice work around since I enjoy the mod- But such doesn't seem to be anywhere. Perhaps I'm looking in the wrong place, but I can't find anything on the "configs".

Anyways, thank you for your time! I wish to add more info, but I'm still quite new to Minecraft Java.

**Comment by Jeryn99** [comment]
Hello! This issue is actually a duplicate of another issue but to answer your question 

The angel theft is controlled by data packs, this bug will be fixed very soon

**Comment by Izanagi007** [comment]
Got it, glad to hear it's being worked upon! Thank you!

**Comment by Izanagi007** [comment]
My apologies to annoy once more, but could it be possible to add a way to disable "angel theft" through configs? It would be a bit more accessible if a bug like this or similar occurs again in the future. I don't know how to work with data packs myself, so I sincerely ask if it would be possible to add such a feature. Regardless, the mod is truly amazing! I appreciate all the work put on to it! Thanks again for the time, have a good day!
