### ISSUE TITLE
Making the angels kill the player (46.0.1, minecraft version 1.20.1, fabric)

### ISSUE THREAD

**Issue by cec1Ie** [ReallySub/Weeping-Angels-Mod#334]
In the curseforge comments section you mention 'You cannot disable climbing - you can make them kill instead by changing the config' in reply to another user, but there is no section for this in the config. How do you make them kill the player?

**Comment by Jeryn99** [comment]
Depends on Minecraft version, you have not supplied your mod version, minecraft version or mod loader...

**Comment by cec1Ie** [comment]
mod version 46.0.1, minecraft version 1.20.1, fabric. sorry, this was one of my first posts on github (but thank you for telling me the correct way of posting things!)
