### ISSUE TITLE
How do I disable teleportation between dimensions?

### ISSUE THREAD

**Issue by elpideus** [ReallySub/Weeping-Angels-Mod#335]
I have a lot of dimensions and it would be a real hassle typing each and every one of them in the banned_dimensions array.

**Comment by Jeryn99** [comment]
Minecraft Version? Mod Version? Forge? Fabric? 😳

**Comment by elpideus** [comment]
Minecraft: 1.19.2
Mod: 43.0.9
Fabric: 0.14.24

**Comment by Jeryn99** [comment]
Added Config for next version
