### ISSUE TITLE
Extreme block lag when weeping angels are nearby

### ISSUE THREAD

**Issue by Dausora** [ReallySub/Weeping-Angels-Mod#336]
Hope you're well,

I'm on 1.19.2, for reference.

I noticed heavy block lag (even in the overworld) with weeping angels nearby to me; breaking blocks, the item wouldn't drop and the block would come back five or six times before it finally actually broke and dropped, and this was pretty much everything I tried to break until the angel wasn't near me for whatever reason.

In the Nether this was even worse due to their incredibly high spawn rate. I'm imagining the block lag is something like an incompatibility with one of the other mods I've got active, since most people seem to not be struggling at all with this; I haven't seen anyone else mention this as an issue.

I installed the mod Observable to get a better view of what's going on; linked are the results of a single Observable test whilst within the Nether with between two and five naturally-spawned weeping angels nearby. (https://o.tas.sh/#q9WMB)

Or, from the aggregate results in that link, a copy-paste of the topmost portion in case you aren't comfortable opening the link. Other important information such as my mods list is within the link but I can copy-paste that if you'd prefer.

weeping_angels:weeping_angel | 72321 us/t (7875 ticks)
minecraft:zombified_piglin | 769 us/t (8688 ticks)
minecraft:strider | 748 us/t (5321 ticks)
minecraft:skeleton | 487 us/t (4823 ticks)
minecraft:piglin | 378 us/t (1205 ticks)
minecraft:enderman | 258 us/t (2895 ticks)
minecraft:pig | 239 us/t (1170 ticks)
minecraft:player | 144 us/t (242 ticks)
quark:foxhound | 122 us/t (1205 ticks)
minecraft:fox | 119 us/t (1040 ticks)
minecraft:ghast | 76 us/t (241 ticks)

Let me know if any more information or testing would be helpful, e.g. testing what it's like if I removed certain mods. Thanks for your time!

**Comment by Jeryn99** [comment]
Should be fixed for next 1.19.2 version
