### ISSUE TITLE
Game crashes whenever it renders a angel (atleast 1.19-1.20.1)

### ISSUE THREAD

**Issue by randomyvery** [ReallySub/Weeping-Angels-Mod#338]
if an angel spawns naturally or i spawn one (whether it be a statue or alive version) the games freezes, saves the world then crashes. weirdly enough it doesnt have problems if i open minecraft through the curseforge app. this happens to my friend too. i tried without any other mods and it still crashes. seems to not change with different variants of angels.
the details of this crash are from 1.20.1, but it still crashes when i tried other minecraft versions.
exit code:-1
error description:The game crashed whilst rendering entity in world
Error: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: weeping_angels:textures/entity/angel/alice/variants/dirt/dirt_angel_\u0131dle.png
[crash-2024-01-15_19.23.49-client.txt](https://github.com/Suff99/Weeping-Angels/files/13941155/crash-2024-01-15_19.23.49-client.txt)

**Comment by randomyvery** [comment]
nvm i fixed it just needed to change my language. same thing as #282

**Comment by Jeryn99** [comment]
Fixed
