### ISSUE TITLE
Limits the spawning of Weeping Angels

### ISSUE THREAD

**Issue by qdazi2** [ReallySub/Weeping-Angels-Mod#339]
I'd suggest limiting the number of Weeping Angels spawns or changing the spawn conditions, as the number of spawns is too much and too fast. Sometimes just doing something, looking back at a bunch of Weeping Angels can really affect the balance of the game as well as the smoothness of the game.

**Comment by Jeryn99** [comment]
This is a bug, it had a fix that’s pending release (version dependent)
