### ISSUE TITLE
Weeping Angels not taking damage

### ISSUE THREAD

**Issue by Jedrysek** [ReallySub/Weeping-Angels-Mod#341]
The weeping angles aren't taking damage with any tool, pickaxe, shovel and even the generator doesn't do anything.

I have not edited any config files or anything else.
I'm on Minecraft version 1.20.1 and forge version 47.2.0.
This issue is happening in the nether and overworld.

**Comment by Revenge2K** [comment]
I have that same problem  . There is only the mossy stone looking one. Version 1.19.2
