### ISSUE TITLE
cant disable dimension teleporting

### ISSUE THREAD

**Issue by JokiSTM** [ReallySub/Weeping-Angels-Mod#343]
no way to turn it off all together on the 1.20.1 fabric port, makes them unplayable since some dimension mods basically leave you stuck in that dimension with no way out, also should be an option to turn off the item deletion

**Comment by Jeryn99** [comment]
Yes there is: https://github.com/Suff99/Weeping-Angels/blob/5d1f127835fa635b4878d02eec35e5b1eb9951d1/common/src/main/java/mc/craig/software/angels/WAConfiguration.java#L91


And once again, yes there is:
https://github.com/Suff99/Weeping-Angels/blob/5d1f127835fa635b4878d02eec35e5b1eb9951d1/common/src/main/java/mc/craig/software/angels/common/entity/angel/WeepingAngel.java#L211

**Comment by JokiSTM** [comment]
i might just be too stupid to figure out how to turn those things off because when i go into the config i dont see any of that

**Comment by Jeryn99** [comment]
STEALABLE_ITEMS are defined with a datapack, you make a empty datapack to disable

And what config file are you opening?

**Comment by JokiSTM** [comment]
the config im opening is weeping_angels-common.toml in the config folder

**Comment by Jeryn99** [comment]
Can you paste its contents here?

**Comment by JokiSTM** [comment]
[behaviour]
	#This section determines the behaviour of the Weeping Angels - if you wish to ban a block from being interacted with by Weeping Angels, you will need to create a datapack and edit weeping_angels:no_breaking
	#Determines the range quantum locked entities will check if the player is looking in
	#Range: 1 ~ 100
	stalk_range = 65
	#If enabled alongside the mobGriefing gamerule, angels will interact with blocks that emit light
	block_breaking = true

[damage]
	#Hurt
	#Allowed Values: PICKAXE, PICKAXE_AND_GENERATOR, NONE, GENERATOR, ANYTHING
	hurt_type = "PICKAXE_AND_GENERATOR"

[teleporting]
	#Determines the range that a player can be teleported from their current location
	#Range: > 1
	teleport_range = 400
	#Determines the chance a player will be teleported
	#Range: 1 ~ 100
	teleport_chance = 50
	#A list of Dimensions that angels cannot teleport players to
	banned_dimensions = ["minecraft:the_end"]

**Comment by JokiSTM** [comment]
theres also a weeping_angels-client.toml one but its only option is enabling santa hats
