### ISSUE TITLE
Weeping Angel mod incompatible and made for an older version of minecraft? [forge 1.20.1]

### ISSUE THREAD

**Issue by SHI-FTL0CK** [ReallySub/Weeping-Angels-Mod#344]
Im playing on 1.20.1 and installed mods with the same version, I'm also on forge. I've downloaded the weeping angel mod twice, both with the version 1.20.1 because obviously all my mods are in that version, but now whenever i hover over the mod in minecraft, (data packs area) it just says incompatible (made for an older version of minecraft). i also havent seen any of ythem in game. im really confused, help? 
![help](https://github.com/Jeryn99/Weeping-Angels/assets/163038153/18a6ca53-59b3-49c0-8e21-08b53595a53c)

(im also new to github, cursed forges and recently just started playing minecraft again after some years)

**Comment by Jeryn99** [comment]
Hi, you can ignore the data pack warning - I just forgot to update a number, it won’t affect anything 

As for the speaking, you likely have them at default values which is incredibly rare
