### ISSUE TITLE
forge 1.20.1 teleporting to other dimension

### ISSUE THREAD

**Issue by pizzav-xyz** [ReallySub/Weeping-Angels-Mod#345]
when i get attacked by a [weeping angel](https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/4598591) i get teleported to i get teleported to the dimension graveyard:past i assume its from [this mod](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-forge), how do i get out of this dimension and prevent this from happening again.

these are other mods

- [Horror Element Mod](https://www.curseforge.com/projects/496520) [1.5.7]
- [Autofish](https://minecraft.curseforge.com/projects/autofish) [0.9.10-SNAPSHOT]
- [Connector-1.0.0-beta.37+1.20.1](https://modrinth.com/mod/connector)
- Forgified Fabric API [0.92.0+1.11.3+1.20.1]
- [Lazurite](https://github.com/Su5eD/Lazurite) [1.0.3+mc1.20.1]
- ImmediatelyFast [1.2.10+1.20.4]
- .connector
- [Wool Recipes](https://modrinth.com/mod/SKFVc5Xz) [1.6]
- [Forgematica](https://modrinth.com/mod/dCKRaeBC) [0.1.3-mc1.20.1]
- oωo [0.11.2+1.20]
- [Smooth Boot (Reloaded)](https://modrinth.com/mod/smooth-boot-reloaded) [0.0.4]
- [TexTrue's Embeddium Options](https://modrinth.com/mod/S1tndFDa) [0.1.5+mc1.20.1]
- [Kotlin for Forge](https://modrinth.com/mod/ordsPcFz) [9j6YaPp2]
- [Canary](https://www.curseforge.com/minecraft/mc-mods/canary) [0.3.3]
- EntityCulling [1.6.2]
- [Entity Texture Features](https://modrinth.com/mod/BVzZfTc1) [5.2.3]
- [FastQuit](https://modrinth.com/mod/fastquit) [3.0.0+1.20+]
- [Resourcify](https://modrinth.com/mod/RLzHAoZe) [1.3.1]
- Ferrite Core [6.0.1]
- [FirstPerson](https://modrinth.com/mod/H5XMjpHi) [2.3.4]
- [Entity Model Features](https://modrinth.com/mod/4I1XuqiY) [1.3]
- [Enhanced Block Entities](https://github.com/FoundationGames/EnhancedBlockEntities) [0.9+1.20]
- [Saturn](https://legacy.curseforge.com/minecraft/mc-mods/saturn) [0.1.3]
- [cave_dweller](https://www.curseforge.com/projects/921557) [1.6.4]
- [MaFgLib](https://modrinth.com/mod/SKI34J7B) [0.1.8-mc1.20.1]
- [AmbientSounds](https://www.curseforge.com/projects/254284) [5.3.9]
- [Smooth Swapping](https://modrinth.com/mod/smooth-swapping) [0.9.3.1]
- [The Graveyard](https://www.curseforge.com/projects/531188) [3.1]
- [Equipment Compare](https://modrinth.com/mod/CYSUVOdj) [1.3.7]
- [Iceberg](https://modrinth.com/mod/5faXoLqX) [1.1.21]
- [WI Zoom](https://modrinth.com/mod/o7DitHWP) [1.5-MC1.20.1-Forge]
- Broken Lead Warner [1.1.1+1.20.x]
- [ModernFix](https://modrinth.com/mod/modernfix) [5.13.0+mc1.20.1]
- [Architectury](https://modrinth.com/mod/lhGA9TYQ) [9.2.14]
- [Dynamic Name Tags](https://modrinth.com/mod/fvuBCsyX) [1.0.0]
- [FPS Reducer](https://minecraft.curseforge.com/projects/fps-reducer) [1.20-2.5]
- [GeckoLib 4](http://geckolib.com/) [4.4.2]
- [Weeping Angels](https://modrinth.com/mod/TEzJJY7H) [46.0.1]
- [Double Doors](https://modrinth.com/mod/JrvR9OHr) [5.2]
- Cull Less Leaves Reforged [1.20.1-1.0.5]
- [Cloth Config v10 API](https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge/) [11.1.118]
- [Fabric Language Kotlin](https://minecraft.curseforge.com/projects/fabric-language-kotlin) [1.10.19+kotlin.1.9.23]
- [Sleep Time](https://www.curseforge.com/projects/641580) [1.20.1]
- [EnhancedVisuals](https://modrinth.com/mod/KjL0jE2w) [1.6.9]
- [Collective](https://modrinth.com/mod/e0M1UDsY) [7.36]
- [Stack to Nearby Chests](https://github.com/xiaocihua) [0.5.4]
- [Tweakerge](https://modrinth.com/mod/yke6wdGF) [0.1.2-mc1.20.1]
- Dynamic Music [2.3.2+1.20]
- [Clock HUD](https://modrinth.com/mod/58HcosC7) [2.0.0-mc1.20.1]
- [MidnightLib](https://modrinth.com/mod/codAaoxh) [1.4.2]
- [Auto Flight Elytra](https://modrinth.com/mod/GPL463SO) [1.0.0]
- [Easy Elytra Takeoff](https://modrinth.com/mod/3hqwGCUB) [4.2]
- [Oculus](https://modrinth.com/mod/GchcoXML) [1.6.15a]
- [Your Items Are Safe](https://modrinth.com/mod/lL35xmSR) [4.0]
- [Quick Menu](https://github.com/ImCodist/quick-menu) [1.2.3]
- [Sound Physics Remastered](https://modrinth.com/mod/qyVF9oeo) [1.20.1-1.3.1]
- [Disconnect Keybind](https://modrinth.com/mod/disconnect) [1.2.1]
- [The Man From The Fog](https://modrinth.com/mod/hIZHlLOF) [1.0.0]
- [Embeddium](https://modrinth.com/mod/sk9rgfiA) [0.3.7+mc1.20.1]
- [CreativeCore](https://modrinth.com/mod/OsZiaDHq) [2.11.24]
- [ItemSwapper](https://github.com/tr7zw) [0.5.3-mc1.20.1]
- [From The Fog](https://modrinth.com/mod/p1WH6sHr) [1.9.2]
- [Connector Extras](https://github.com/Sinytra/ConnectorExtras) [1.10.0+1.20.1]

**Comment by MCraftBoatBloke** [comment]
No dimensions are added by the Weeping Angel mod. That dimension is added by a different mod, no idea which one.

**Comment by pizzav-xyz** [comment]
> No dimensions are added by the Weeping Angel mod. That dimension is added by a different mod, no idea which one.

i said which mod i asume it was from but i am certain the weeping angel sends me there

**Comment by Jeryn99** [comment]
@MCraftBoatBloke The reporter has hyperlinked the mod that adds it 

I do not know how you leave this dimension as it's not my mod, but you can use commands to change dimension 


In order to stop this in future, disable dimensional teleporting in your configuration

**Comment by pizzav-xyz** [comment]
> @MCraftBoatBloke The reporter has hyperlinked the mod that adds it
> 
> I do not know how you leave this dimension as it's not my mod, but you can use commands to change dimension
> 
> In order to stop this in future, disable dimensional teleporting in your configuration

how do i disable dimensional teleporting in your configuration

**Comment by pizzav-xyz** [comment]
@Jeryn99

**Comment by Jeryn99** [comment]
You open the weeping angels config file from the config folder in your favourite text editor

**Comment by pizzav-xyz** [comment]
> You open the weeping angels config file from the config folder in your favourite text editor

only thing i see about dimension is this

	#A list of Dimensions that angels cannot teleport players to
	banned_dimensions = ["minecraft:the_end"]
