### ISSUE TITLE
[Forge][1.20.1] Permission to adapt textures for modpack

### ISSUE THREAD

**Issue by pinkygrocket** [ReallySub/Weeping-Angels-Mod#349]
Hello, not sure where to ask this question since the Discord invite is down, so figured I would ask here.

Since this mod's assets are licensed under All Rights Reserved, I would like permission to alter the pre-existing assets for a personal modpack that I will release via Curseforge. Neither the pack itself or its custom assets will be sold.

**Comment by Jeryn99** [comment]
You mean like a resource pack? 

https://discord.gg/mjqEYAp2Nq

**Comment by pinkygrocket** [comment]
Basically yes.
