### ISSUE TITLE
changing spawn biomes causes atlas stitching

### ISSUE THREAD

**Issue by sandwichwater** [ReallySub/Weeping-Angels-Mod#351]
i have no idea why in the world this is , and i know it doesnt make any sense , but whenever i try to add any biomes to the config file for spawning angels the game loads everything just fine until it reaches "Atlas Stitching: minecraft:textures/atlas/shulker_boxes.png" which it then hangs until crashing . if i remove the added biomes it loads just fine , but even just one additional biome than the default config and this issue pops right back up . again , i know it doesnt make sense for editing a config file to affect anything to do with texture stitching but i really have no other ideas , add biomes and i get the issue , have only the default ones and it launches fine . any help would be so appreciated

edit : on version 1.16.5

**Comment by Jeryn99** [comment]
uhh? what?

**Comment by sandwichwater** [comment]
for some reason i cannot add any new biomes to the spawn list and i have no idea why , i dont even know why changing spawn biomes in specific causes this error , if it makes any difference it happens both playing with other mods and with this being the only mod with no luck
