### ISSUE TITLE
Crashes when teleporting me or being summoned

### ISSUE THREAD

**Issue by Revenge2K** [ReallySub/Weeping-Angels-Mod#353]
In the mode, the green stone angel (mossy stone) cannot be damaged by the pickaxe, and some stone angels turn into a purple pattern when following me. Also, sometimes they have pickaxes on their heads (texture error).

**Comment by Jeryn99** [comment]
You need to make sure that the level of pickaxe you have, can damage the weeping angels "material"

For example, if the weeping angel represented a dirt angel, youd want to use a shovel instead 

If they have pickaxes above their head, it means it has a stolen item from a player 


The purple pattern is a texture error, next time it happens, upload your log file so I can find out which one it is

**Comment by Revenge2K** [comment]
[crash-2024-05-08_01.48.42-client.txt](https://github.com/Jeryn99/Weeping-Angels/files/15241968/crash-2024-05-08_01.48.42-client.txt)

Also my game crashed when I summoned a weeping angel

**Comment by Jeryn99** [comment]
Are you playing on a operating system thats running a different language than english? This is a bug I have been meaning to look into

**Comment by Revenge2K** [comment]
Yes, I use Turkish language. But could the crash have something to do with it?

**Comment by Revenge2K** [comment]
By the way, I didn't know that the mossy angel was broken with a shovel, my bad :/
