### ISSUE TITLE
1.19.2 Plinth Texture Issue

### ISSUE THREAD

**Issue by MrPerc** [ReallySub/Weeping-Angels-Mod#354]
The plinth, if placed on a wall, will remove the texture of the block behind it. 
![Screenshot 2024-05-14 201456](https://github.com/Jeryn99/Weeping-Angels/assets/169859395/4918763b-5635-4ba0-ac8a-8669112aa614)

**Comment by Jeryn99** [comment]
Hey, is this Forge or Fabric?
