### ISSUE TITLE
[Forge 1.20.1] Teleporting above bedrock roof

### ISSUE THREAD

**Issue by polykatt** [ReallySub/Weeping-Angels-Mod#356]
Encountered a weeping angel in the nether that teleported me above the bedrock roof layer in the Otherside dimension (Deeper and Darker mod). Not sure if its an issue with the fact that the location was a modded dimension but being teleported above bedrock roof is a major grief.

I guess this is a bug report or a suggestion - please make this scenario impossible ^-^

**Comment by k2helix** [comment]
This also happens in Fabric 1.20.1 in the Nether with Amplified Nether installed.

**Comment by JasdanVM** [comment]
This also happens in Fabric 1.20.1 with Incendium and Tectonic.

**Comment by VertexBufferObject** [comment]
This has happened to me and I'm not sure what to do. I have the 46.0.2 fabric running and I'm wondering if this is still a bug or just something I haven't figured out yet?

**Comment by AlfredoCoal** [comment]
I'm running a server on forge with the Deeper and Darker mod, I had to just disable interdimensional teleporting. My other issue is that players are being sent to the nether roof, which I presume is also due to amplified nether.

**Comment by Jeryn99** [comment]
Resolved for 1.19.2 and 1.20.1
