### ISSUE TITLE
Chisel Does Nothing

### ISSUE THREAD

**Issue by pax-wax** [ReallySub/Weeping-Angels-Mod#357]
Whenever I try to use the chisel on a statue, exiting the menu makes none of the changes I applied. I'm using 1.20.1. I also noticed that the placeable angels and coffin need to be broken twice before they will actually disappear.

**Comment by thankfuldeadman** [comment]
yes, I have the same problem

**Comment by thankfuldeadman** [comment]
I had to hold down the up arrow key and spam the enter key for it to work

**Comment by Jeryn99** [comment]
I'll try get this fixed soon, been working on Tardis Refined a lot lately
