### ISSUE TITLE
FABRIC 1.20.1, all mobs teleporting \_O_O_/ ?

### ISSUE THREAD

**Issue by KawaiiKichaneKusuteki** [ReallySub/Weeping-Angels-Mod#359]
Hewwo,

I poped in today to say really thank's for your modding ideas, i really enjoy it. But i've a issue please ! I installed FABRIC 1.20.1 version of Weepings Angels, but all, completely all creatures are teleporting when i hit them D: ! please help me !

Thank's for your attention, stay healthy, bobye~~

**Comment by Jeryn99** [comment]
Do you have a video of this issue? I cannot replicate it
