### ISSUE TITLE
Catacombs create a huge number of empty stone chambers (often floating above water or in mid-air)

### ISSUE THREAD

**Issue by KnightCa** [ReallySub/Weeping-Angels-Mod#360]
```
        # Generate catacombs?
        B:genCatacombs=true
```

When generating, there is a large number with no weeping angels and with the stone chambers generating in mid-air.

![image](https://github.com/Jeryn99/Weeping-Angels/assets/51968609/122a33a8-63f4-414c-8fd2-afe18d9ab4a2)

**Comment by Jeryn99** [comment]
Minecraft Version?

**Comment by KnightCa** [comment]
Minecraft 1.12.2On Jun 30, 2024, at 10:26 AM, Craig (Jeryn) ***@***.***> wrote:﻿
Minecraft Version?

**Comment by Jeryn99** [comment]
1.12.2 is no longer supported
