### ISSUE TITLE
Missing an option to disable pickaxe stealing in the config!

### ISSUE THREAD

**Issue by KohlrabitoDev** [ReallySub/Weeping-Angels-Mod#361]
On the latest version, PLEASE, update & add a little toggle for pickaxe stealing. These annoying little shits will just run up behind me, steal my pickaxe, & tp me a 400 block radius away from where I was! This causes them to either despawn, get lost, or just do whatever they want with my fully enchanted diamond pickaxe!

**Comment by Jeryn99** [comment]
You can control this with datapacks.
