### ISSUE TITLE
Angels teleport outside of the worldborder

### ISSUE THREAD

**Issue by Gnarty** [ReallySub/Weeping-Angels-Mod#364]
if you reduce the world border and you are close to it if an angel teleport you can get you outsite the world border

**Comment by Gnarty** [comment]
minecraft 1.20.1

**Comment by Jeryn99** [comment]
Fixed for 1.21: https://github.com/Jeryn99/Weeping-Angels/commit/9afdd69c60400ab84317f5c8c4f49570d862d0d3

Will backport soon

**Comment by Gnarty** [comment]
there is a date for the backport of the fix to the 1.20.1?
