### ISSUE TITLE
Crash when trying to use `snow_angel` item [`Fabric 1.21`]

### ISSUE THREAD

**Issue by mpustovoi** [ReallySub/Weeping-Angels-Mod#367]
When I try to place a snow angel, my game instantly crashes.
Here are the [logs](https://mclo.gs/fD51YrL) and [crash report](https://mclo.gs/pS51hXR).

I had this problem on `Fabric 1.20.1` and `Forge 1.20.1` too.
The only thing that unites these instances of mine is the mod [`Snow! Real Magic! ⛄`](https://modrinth.com/mod/snow-real-magic) mod.
I guess it's a compatibility issue, since when removing this mod, the snow angel works as intended.

`Snow! Real Magic! ⛄` makes a really important contribution to the game, and I wouldn't want to take it away from my instance. However, I also really like your mod that adds an element of fear.
I hope some workaround can be done here.

I'm sorry if this issue has already been raised. I didn't find it by keywords.

**Comment by Jeryn99** [comment]
Perfectly unique new issue! I'll have a look soon

**Comment by Jeryn99** [comment]
Fixed: https://github.com/Jeryn99/Weeping-Angels/commit/9afdd69c60400ab84317f5c8c4f49570d862d0d3

Please download 1.0.2
