### ISSUE TITLE
Offset fix for "Anomalies Detected : 0" 1.21

### ISSUE THREAD

**Issue by makumaku1974** [ReallySub/Weeping-Angels-Mod#369]
![image](https://github.com/user-attachments/assets/9dd4e7e6-51a5-4380-a37a-03e3fad3bd1d)

**Comment by Jeryn99** [comment]
Fixed: https://github.com/Jeryn99/Weeping-Angels/commit/9afdd69c60400ab84317f5c8c4f49570d862d0d3

Please download 1.0.2
