### ISSUE TITLE
Disconnects the World after getting the item Anomaly Detector 1.21

### ISSUE THREAD

**Issue by makumaku1974** [ReallySub/Weeping-Angels-Mod#372]
Anomaly Detector seems to activate a lots of recipes and crashes the world. not the game. 

logs:
https://mclo.gs/grk1gFc

**Comment by Jeryn99** [comment]
Hello. I cannot seem to pinpoint the issue in your logs, but a few things stand out to me

A lot of recipes fail to register, and your Minecraft seems to be pinging 0.0.0.0 for authentication...

Is this legit Minecraft?

**Comment by Jeryn99** [comment]
Ah, I see tlauncher in use - sorry cannot help you
