### ISSUE TITLE
Crash on startup [Forge 1.19.2]

### ISSUE THREAD

**Issue by mpustovoi** [ReallySub/Weeping-Angels-Mod#376]
My game crashes on startup. The logs show errors in the of your mod mixins.
No crash-report, only the [log](https://mclo.gs/oIxTFVi).
The problem wasn't there on the version before latest `[Forge - Weeping Angels - 1.19.2] - v43.1.0`.

I didn't find a similar issue on this version.

**Comment by Jeryn99** [comment]
Does it also happen on Forge?

**Comment by mpustovoi** [comment]
This is what happens on Forge. I don't have a similar instance on Fabric 1.19.2

**Comment by PlgDr-Krow** [comment]
I dont know how to access the same log the OP posted, but I am experiencing the exact same issue on Forge 1.19.2 v43.2.14. Thank you for handling this!

**Comment by Jeryn99** [comment]
Damn forge being Forge, I will have something out by the weekend

**Comment by mpustovoi** [comment]
> I dont know how to access the same log the OP posted

Open the folder of your Minecraft instance, and then go to the `logs` folder. Here you can find your `latest.log`.

**Comment by Renowbrine** [comment]
> Damn forge being Forge, I will have something out by the weekend

okay, are you still going to release something by the weekend?

**Comment by Jeryn99** [comment]
Became a bit more complicated than what I first thought and I also became busy

> > Damn forge being Forge, I will have something out by the weekend
> 
> okay, are you still going to release something by the weekend?

**Comment by Renowbrine** [comment]
> Tornou-se um pouco mais complicado do que eu planejei inicialmente e também fiquei ocupado
> 
> > > Droga, Forge é Forge, vou lançar algo até o fim da semana
> > 
> > 
> > Ok, você ainda vai lançar algo até o fim da semana?

I understand, no problem, I look forward to this wonderful project, I will use the previous version for now

**Comment by mpustovoi** [comment]
Yep, it's still relevant.

**Comment by Jeryn99** [comment]
I've made everyone wait a bit too long on this one due to my development workspace screaming, I've figured out how to fix it so hopefully should have a fix this week
