### ISSUE TITLE
there is no button to confirm the change in Chisel UI

### ISSUE THREAD

**Issue by Foxsik193** [ReallySub/Weeping-Angels-Mod#377]
versions forge 1.20.1

**Comment by Foxsik193** [comment]
![Снимок экрана 2024-08-20 184957](https://github.com/user-attachments/assets/c313aeb7-e925-46f9-8c4f-708918a8ab15)

**Comment by BluePentagram** [comment]
Same with the v1.20.1-46.0.2 for fabric

**Comment by Jeryn99** [comment]
Bot no

**Comment by Foxsik193** [comment]
BOT NO

**Comment by Jeryn99** [comment]
https://github.com/Jeryn99/Weeping-Angels/issues/357
Follow the above issue for updates
