### ISSUE TITLE
does not work in the new 1.19.2 update

### ISSUE THREAD

**Issue by Renowbrine** [ReallySub/Weeping-Angels-Mod#379]
![image](https://github.com/user-attachments/assets/782d119b-0fe4-4332-a607-c4119ba7d486)

**Comment by Jeryn99** [comment]
Duplicate of https://github.com/Jeryn99/Weeping-Angels/issues/375 and https://github.com/Jeryn99/Weeping-Angels/issues/376

Please track https://github.com/Jeryn99/Weeping-Angels/issues/376
