### ISSUE TITLE
1.20.1 Version of the mod causes massive lags on my server.

### ISSUE THREAD

**Issue by 1Bulgarian** [ReallySub/Weeping-Angels-Mod#381]
I run a RolePlay server for Minecraft 1.20.1 and we decided to use this mod, because 1. It add fun and unique mobs and 2. Nobody in our region has watched Dr Who.

The unfortunate part is that the angles cause a LOT of lag when they are moving. For context, 5 people in the server, TPS drops from 20 to 5, when encountering one (or a few) Weeping Angels. Spark also shows 30% Thread usage for mobs, but when you sum up the mobs that are showed there, you get only 20%, therefore 10% is missing somewhere. This was no longer happening once we took the mod out.

We really enjoyed using the mod, both the staff and the community, so we would love it if you could keep the 1.20.1 version updated as well.

**Comment by Jeryn99** [comment]
Hey, you mention all these performance numbers - would you mind giving me your data so I can look into it?

**Comment by Jeryn99** [comment]
Subscribe to https://github.com/Jeryn99/Weeping-Angels/issues/387
