### ISSUE TITLE
Weeping angels reaching 10+ blocks away + through walls

### ISSUE THREAD

**Issue by aplro** [ReallySub/Weeping-Angels-Mod#389]
Version: Forge 1.19.2-43.1.1
Hits you from 10+ blocks away (and snaps your neck as well).
Takes away your pickaxe while looking at it
Spawns in the numbers of 20-30 at all settings including "Maximum 1" in the nether while I have never seen one in the overworld.

**Comment by Jeryn99** [comment]
This kinda sounds like you're experiencing lag more than anything?

If you get me a video of the issue I can look into it happening and attempt to resolve it?

**Comment by Jeryn99** [comment]
Subscribe to https://github.com/Jeryn99/Weeping-Angels/issues/387
