### ISSUE TITLE
Massive Spawnrate of Weeping Angels in Nether Biomes

### ISSUE THREAD

**Issue by WalkerTheHat** [ReallySub/Weeping-Angels-Mod#392]
I'm playing on **Forge 1.19.2**, **Weeping Angels version 43.1.2**, operating on a PebbleHost server with players joining via Prism Launcher.

I am running into an issue after adding Weeping Angels to my modpack. I host a server for some friends and we've quickly encountered that even though I've cranked down weeping angel spawns as low as I can to make them a rare occurence, in the Nether they spawn like wildfire. Walking through a portal holding a Detector and suddenly there's 8 waiting for me. I believe this is because the monster spawn table is much smaller, so there are less options to choose from overall despite their low probability.

Is there a way you'd recommend for me to shut off Weeping Angels from spawning outside the Overworld? I'd honestly like to dwindle their spawn chances much further down in general, but the nether issue is unfortunately unplayable for some of my friends who are seeking a less hardcore experience.

**SPAWN CONFIG CONDITIONS:**
[spawn]
	#The minimum amount of 'Weeping Angels' that spawn at each spawn attempt
	#Range: 1 ~ 100
	minCount = 1
	#The maximum amount of 'Weeping Angels' that spawn at each spawn attempt
	#Range: 1 ~ 100
	maxCount = 1
	#The weight of spawn in relation to other mods 'Weeping Angels' will spawn in. Less than 100 = Rarer
	#Range: > 1
	spawn_weight = 2
	#'Weeping Angel' spawn classification
	#Allowed Values: MONSTER, CREATURE, AMBIENT, AXOLOTLS, UNDERGROUND_WATER_CREATURE, WATER_CREATURE, WATER_AMBIENT, MISC
	spawnType = "MONSTER"

**Comment by Jeryn99** [comment]
Datapack 

https://github.com/Jeryn99/Weeping-Angels/blob/architectury/1.19/forge/src/generated/resources/data/weeping_angels/tags/worldgen/biome/spawns/weeping_angels.json
