### ISSUE TITLE
The config file does nothing

### ISSUE THREAD

**Issue by TK19020** [ReallySub/Weeping-Angels-Mod#393]
I create a world and the mod was incredible but when i go to the nether, the spawns rates in the warped biome made me unable to farm enderperls, and it was excesive, whe i open the config file, and make changes it does nothing

I dont know if im doing something wrong or what i need to do

Forge 
1.20.1
WA 46.0.2

**Comment by Jeryn99** [comment]
Subscribe to https://github.com/Jeryn99/Weeping-Angels/issues/387
