### ISSUE TITLE
Interdimensional Teleporation Not Working In Fabric 1.20.1

### ISSUE THREAD

**Issue by SamMcClatchey** [ReallySub/Weeping-Angels-Mod#395]
I have been messing with the config and letting myself be teleported for hours in all 3 versions available for 1.20.1 with no other mods installed and I have yet to be teleported to the Nether.

**Comment by Jeryn99** [comment]
Random Coordinates + Nether = bad

It will rarely find a good teleport position via randomness without ending up on the roof
