### ISSUE TITLE
Crash 1.20.1 

### ISSUE THREAD

**Issue by Eriuis** [ReallySub/Weeping-Angels-Mod#396]
Crash when starting the server with the new version [Forge] Weeping Angels - v1.20.1-46.1.0

Server Crash: [crash-2024-12-17_11.07.27-server.txt](https://github.com/user-attachments/files/18169187/crash-2024-12-17_11.07.27-server.txt)

Forge Version: 47.3.12
Minecraft; 1.20.1
Loader: Forge

**Comment by Jeryn99** [comment]
Strange, it's a easy fix but this is because it couldn't check if a biome exists in the config

Do you have datapack biomes installed or another mod that installs biomes?

**Comment by Eriuis** [comment]
I removed all mods to try Weeping Angels and it still crashes, I have no datapacks installed, only Weeping Angels, I deleted the "config" folder, made a new world and it still crashes

**Comment by Jeryn99** [comment]
Just fixed it for 1.19.2, going to put it up for release and then sort out 1.20.1 

Will all be sorted tonight!

**Comment by Jeryn99** [comment]
Uploaded to curse and modrinth now :)
