### ISSUE TITLE
Modded Dimensions is either over-run by Weeping Angels or not at all

### ISSUE THREAD

**Issue by arkeniann** [ReallySub/Weeping-Angels-Mod#399]
I was trying to make a Minecraft x Doctor Who Modpack, and inside of the Modpack, I installed this Mod and many Dimensions Mods (because I also installed a TARDIS Refined so I have more dimensions to explore). When I checked other dimensions, I noticed that some Modded Dimensions spawned too many Weeping Angels or did not spawn at all. Here's what I found:

- Aether Mod: Over-run by Weeping Angels (350+ Entity)
- Deeper and Darker Mod: Over-run by Weeping Angels (500+ Entity)
- Blue Skies Mod: Both Everdawn and Everbright dimensions seem to not have any Weeping Angels
- Undergarden Mod: around 15-25 Weeping angels
- Ad Astra Mod: I've only checked a few places from this mod and it seems that they also don't have any Weeping Angels

Version : 1.20.1
Mod Loader : Forge
Loader Version : 47.3.0
Mod Version : 46.1.5

**Comment by Jeryn99** [comment]
You have a config to disable these biomes and change the numbers, Minecraft has horrible fragile spawns code
