### ISSUE TITLE
Sound spam??

### ISSUE THREAD

**Issue by Efimero** [ReallySub/Weeping-Angels-Mod#7]
The angelSeen sound seems to play multiple times per frame when it's triggered, 'cause the asset volume is fine and it's set to play at 0.5 volume, but IT IS DEAFENING even when set to play at 15% with Dynamic Surroundings individual sound volume slider ;w;
plz fix, this kitten's ears got hurt <3
https://github.com/ReallySub/Weeping-Angels-Mod/blob/c059a5b9021cfbfbdda6a8acdf8ffc5d5ef53114/src/main/java/com/github/reallysub/angels/main/AngelUtils.java#L99

**Comment by ReallySub** [comment]
I think I fixed this already a few commits ago, but didn't put it on CurseForge yet due to ModJam's voting not being ended yet, try with this and get back to me: https://github.com/ReallySub/Weeping-Angels-Mod/releases/tag/7.0

<3

**Comment by Efimero** [comment]
that went wrong D:
the moment I spawned an angel with that jar, every light block in the area exploded into a fountain of items of itself
meanwhile the sound kept playing every frame until a turret killed the angel
then I had to close the server 'cause it went to <1FPS ;w;
why you want my Minecraft dead, sub? XD
just ping me when you get the next stable <3

**Comment by ReallySub** [comment]
Can I ask, does this sound error only happen with Dynamic sounds installed? @Efimero

**Comment by ReallySub** [comment]
I've fixed this on stream, I'll get a build out later...

**Comment by ReallySub** [comment]
@Efimero https://github.com/ReallySub/Weeping-Angels-Mod/releases/tag/7.5
There you go, should also be on curse forge soon too
