### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Sans3213** [ReallySub/Weeping-Angels-Mod#9]
i have no other mods in my mods folder yet when i click to play forge 1.12.2 its loads for 30 seconds and i get an error like this:
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: com.github.reallysub.angels.common.items.ItemDetector.setTileEntityItemStackRenderer(Lnet/minecraft/client/renderer/tileentity/TileEntityItemStackRenderer;)V

**Comment by ReallySub** [comment]
Update forge and make sure you have the up to date profile selected in your launcher
